### ISSUE TITLE
BUG , deepin doesn't recognize the asociation .jar 

### ISSUE THREAD

**Issue by chemel9** [linuxdeepin/developer-center#1080]
deepin does not recognize the asociation .jar
jre is already installed

![DeepinScreenshot_synaptic_20190413192226](https://user-images.githubusercontent.com/26883220/56086749-e24b5e80-5e22-11e9-8921-272651626f7b.png)

 but in deepin 15.9.3 doesn't recognize the asociation .jar
![deepin-screen-recorder_Desktop_20190413193452](https://user-images.githubusercontent.com/26883220/56086773-4ec65d80-5e23-11e9-9c8f-78c9573e81a0.gif)

Could you fix this bug?

**Comment by BLumia** [comment]
Install jre doesn't means it will let you double click a jre to run something. We also cannot detect if this jar file can be run via `java -jar <name.jar>`.

If you would like to do it, you need manually run it via a terminal emulator or set a default program via the "open with" menu.

**Comment by chemel9** [comment]
with installing jre, it's supposed to run the java application, it's logical

if i select open with , it doesn't show java.
![DeepinScreenshot_dde-file-manager_20190414155915](https://user-images.githubusercontent.com/26883220/56099135-aec60e00-5ece-11e9-9ebd-e06466526466.png)

this is bug of deepin.
in previous versions of deepin, that did not happen

**Comment by BLumia** [comment]
> with installing jre, it's supposed to run the java application, it's logical

Not all `.jar` files can be directly run via `java -jar %f`, that's the problem, we cannot just allowed user "run" a "java application" via double click because we even doesn't know if it is a java application or not. Some java package is also with `.jar` extension/suffix but it simply is not runnable.

> in previous versions of deepin, that did not happen

By saying "previous", which version did you mean?

**Comment by hualet** [comment]
How about give jars special treatments like what we do to AppImages?

**Comment by BLumia** [comment]
> How about give jars special treatments like what we do to AppImages?

Personally I don't think that's a good idea. Since it is only a really few mount of `.jar` file can be run directly via `java -jar`

**Comment by hualet** [comment]
> > How about give jars special treatments like what we do to AppImages?
> 
> Personally I don't think that's a good idea. Since it is only a really few mount of `.jar` file can be run directly via `java -jar`

For those jar files that are not executable, people won't even double click on them I think. What do you think?

**Comment by felixonmars** [comment]
Wouldn't binfmt be the right way to go? Something like https://packages.debian.org/sid/jarwrapper should work.

**Comment by hualet** [comment]
> Wouldn't binfmt be the right way to go? Something like https://packages.debian.org/sid/jarwrapper should work.

The basic assumption here is that the binfmt is configured properly(which is by default I think), and file manager doesn't treat jars as executables.

**Comment by BLumia** [comment]
> For those jar files that are not executable, people won't even double click on them I think. What do you say?

Personally I use double click to open `.jar` file as a normal zip format archive file so I can navigating the archive and find the assets I want. I got a bunch of J2ME games (with `.jar` suffix of course) and JavaEE library packages, nether of them can be run directly via `java -jar`.

AppImage file is designed to be like an app that run anywhere, but jar file is just a Java ARchive. User should know how to use the jar file they got, so if user know it is a runnable java application, simply adding the executable flag via the right-click property dialog, and double-click should works fine (if binfmt is configured properly).

By default there is no Java jar binfmt configurations btw :/

> Something like https://packages.debian.org/sid/jarwrapper should work.

Yep, but the problem is, when user just double-click a normal jar file without execute permission flag, should the file manager ask user to add execute permission and run this jar file as application, just like AppImage files?

**Comment by chemel9** [comment]
in ubuntu ,works correctly , so this is a problem of deepin , i think that the developers should chek this incovennient with the jar files
![simplescreenrecorder-2019-04-20_23 05 52_52](https://user-images.githubusercontent.com/26883220/56465361-8011d100-63c1-11e9-9127-a7ebf1bfb741.gif)
