### ISSUE TITLE
Install on Arch Linux fails (Github release))

### ISSUE THREAD

**Issue by seniordevel** [linuxdeepin/developer-center#10908]
### SUMMARY | 问题概要

With the Github release build fails at the very beginning

`Failed to prepare transaction
could not satisfy dependencies:
- unable to satisfy dependency 'dtkwm' required by deepin-system-monitor-git`

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin-system-monitor version 5.6.12.r1.g91f17ae-1

Operating System: Manjaro Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.8.0
Qt Version: 6.7.2
Kernel Version: 6.10.13-3-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × AMD A10-7870K Radeon R7, 12 Compute Cores 4C+8G
Memory: 14,6 GiB of RAM
Graphics Processor: KAVERI
```

### PRE-REQUIREMENT | 预置条件

...

### STEPS TO REPRODUCE | 复现步骤

...

### OBSERVED RESULT | 观察到的结果

...

### EXPECTED RESULT | 期望的结果

...

**Comment by BLumia** [comment]
Seems [dtkwm](https://gitlab.archlinux.org/archlinux/packaging/packages/dtkwm) has been removed from Arch Linux's repo. I'm not sure about Manjaro but you might need to patch the source to remove the dtkwm usage, or provide the dependency by your self.

> deepin-system-monitor version 5.6.12.r1.g91f17ae-1

That's way too outdated. Please consider using a newer version.

I'll close it as won't fix since `5.x` is definitely no longer supported. By the way, if you are interested in porting DDE/deepin applications to Arch Linux or Manjaro, consider join the porting group at <https://t.me/ddeport>. If you have other **questions** related to porting and not sure if it's a bug, please consider using the [discussion board](https://github.com/linuxdeepin/developer-center/discussions) instead of the issue board. Thanks!
