### ISSUE TITLE
drive speed affects on latency of dde-file-manager

### ISSUE THREAD

**Issue by damhiya** [linuxdeepin/developer-center#1100]
## Describe the bug
When I access slow external hard drive using dde-file-manager, it's reaction becomes very slow. It affects to the whole part of the program. For example, opening files or scrolling the view.

## To Reproduce
Mount any slow external drive and access it using dde-file-manager

## Expected behavior
I don't know much about dde-file-manager's internal structure, but it seems it happening because program's disk operation parts are not separated from the main event loop.

I think multithreading or multiprocessing is the unique solution.

### Distro & Version
Arch Linux

### Related package version
dde-file-manager 1.8.2

**Comment by keybreak** [comment]
Are you sure that it's related to drive itself, and not it's content?

For example on Manjaro Deepin my **/usr/bin** have ~3400 files, and when you scroll it lags regardless of it's SSD / HDD

**Comment by SoonWonMoon** [comment]
Both of them are related.

My /usr/bin is on SSD and contains more than 4500 files but I can open it using dde-file-manager very smoothly.
However, I can fill difference when I open any folder on my external hdd even for the folders which has less than 10 elements. The symptom becomes deepening for large folders

When I open same external drive using nautilus, It takes time to load file list, but it dosen't affect to It's UI latency.

**Comment by keybreak** [comment]
@BLumia @hualet 
I actually confirmed it now, it's HUGE problem that needs to be addressed & solved.
Because it's actually affects any drive (SSD / HDD), not only external.

Easiest test case:
1. Run something really intensive on any drive, like for example **hashdeep** for whole drive's files:
```
hashdeep -c md5 -e -l -r "." > checksum.hash
```
2. Try to move window, or open new one, it will be super slow, file-manager can throw 'not responding window' etc etc

At first i thought it's IO-scheduler's problem or something, i've tried bfq / bfq-mq / mq-deadline to confirm - nope, it's specifically **deepin-file-manager** becomes very unresponsive if active at all.

Any other programs works and opens flawless while same process, and this was tested on extremely powerful machine, so...I really doubt it's hardware related at all

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
