### ISSUE TITLE
Manjaro Deepin File Manager Not Copying Properly

### ISSUE THREAD

**Issue by marcelb3** [linuxdeepin/developer-center#1114]
## Describe the bug

I'm using Manjaro Deepin File Manager to copy about 2tb of files in a folder from one internal hard drive to another.  The folder has a lot of sub folders at up to 5 levels deep.  It takes about 2 hours to do the job.  But, the problem is that not all of the sub folders and files are copied over to the destination drive.  There are no errors reported after the copying process.  

 I have had to find out which folders and files were not copied and copy and paste them over again.  This worked, so it can't be a permissions issue, but surely it should do the initial copying process accurately and without missing anything in the first place.  

Both hard drives are new and in working order.   Could this be an issue with the volume of files being copied?  Could it be the screen saver kicking in?  Is there a buffer setting that needs increasing?   I'm really enjoying using Linux but I'm worried that my files might go missing unless I manually check all the time.   Can anyone help?

**Comment by keybreak** [comment]
That must be fixed if it's bug and not permissions! :scream: 
Loosing files over simple operation is utterly unacceptable.

**Comment by BLumia** [comment]
Any details about how to reproduce it? Seems works fine on my machine. Thanks.

**Comment by keybreak** [comment]
@BLumia 
Confirmed, this is really **serious** issue and must be fixed asap! :disappointed: 

Test case:
1. Trying to copy whole NTFS disk (~2.6 Tb of data) to new ext4 disk.
2. Nothing fancy just usual CTRL+A, CTRL+C -> CTRL+V
3. Dialog haven't even started copy process itself (just enumerated files at least it looked that way) than crashed and basically done nothing at all except ~5 Gb of data on new disk.

Nothing in journal, so...can't really say anything more.
But that one is really bad, i can't imagine how this is possible, since it's not like pre-alpha release of deepin-file-manager, and it suppose to do basic operations reliably (since i assume it should be just GUI for actual copy mechanism, we shouldn't reinvent the wheel here?)...

**Comment by zccrs** [comment]
Hi, What are the characteristics of files/folders that are missing during copying?

**Comment by keybreak** [comment]
hi @zccrs 
> What are the characteristics of files/folders that are missing during copying?

Well it's really hard to say since it was just 5 Gb success over 2,6 Tb of overall data...
It's very very mixed data, a little bit of everything. Docs, movies, programs installers...Just assume everything.

File names mostly on english, sometimes rarely on cyrillic / spanish.

>  And what is the package version of this deepin-file-manager?

deepin-file-manager  1:4.8.3-1

Manjaro Deepin Stable

**Comment by keybreak** [comment]
Goddamit sorry guys, it seems to be not copy mechanism problem, it's more of a visual thing.

I accidently hit alt + tab and found out that dialog is stuck on 'can't copy file because name is too long' state, BUT it was completely buried visually, unless you bring it to front with alt+tab.

Again, sorry for the panic.
But still it's big issue for dialog itself (as it just disappeared without my actual input), since it can scare the sh*t out of user.

**Comment by keybreak** [comment]
Each time you have something change in copy dialog / ask for user input, or even copy another file - it completely disappears out of view.

And resets it's position when alt+tab to bring it back.

This is insane.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
