### ISSUE TITLE
Blur the background on Deepin Terminal is broken

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1133]
## Describe the bug
Background blurring does not work on Deepin Terminal. 

## To Reproduce
Open a Deepin Terminal window and go to settings. Find the related option to blur the background and try to enable it.

## Expected behavior
Should blur the background of Deepin Terminal instantly.

## Video
http://sendvid.com/53i3iukk

### Distro & Version
Linux Deepin 15.10

### Note: I freshly installed Deepin 15.10, didn't upgrade from previous versions.

**Comment by keybreak** [comment]
Oh, now i see, you must be using unstable branch right?
Please say it on all your best reports, since it means deepin-kwin bugs as it's what used in there now.

**Comment by gokhanyildirimlar** [comment]
> Oh, now i see, you must be using unstable branch right?
> Please say it on all your latest reports, since it means wm is **deepin-kwin** and it's related bugs as it's what used in there now.

I use the latest stable version of Deepin, clean installation. Yes, these are related to KWin but it's not beta anymore. Thanks, I will add a note to all my reports that I made a fresh installation of Deepin 15.10. This seems like a good idea.

**Comment by keybreak** [comment]
Wait what? It's out of beta on stable in this state???

@BLumia @hualet 

That's seriously bad move.

Now i'm absolutely 100% on board with @aiamuzz [here](https://github.com/linuxdeepin/developer-center/issues/1121) it's extremely d*ck-move to release such raw stuff to stable public.

Huge huge minus to deepin team reputation on this one.
I completely agree with moving to kwin and solving problems, but seriously releasing THIS to public?!?
___

I will think three times now, before continue to support Deepin the way i did before on all fronts everywhere, and making bug-reports the way i did before.

**Comment by gokhanyildirimlar** [comment]
@keybreak, devs actually started a beta program for KWin on the forum but it wasn't very effective as we can see. But the mistake that they have made just now is releasing 15.10 without any beta program. Deepin used to start a beta program for about 2 weeks before releasing the stable Deepin image. They skipped it this time and here we are. 

At the same time, AppStore is in bad condition because of moving Deepin's base from unstable to stable. It wasn't good before also since everything was old and there was no one to take care of it. Two major moves at once with such a small team led Deepin here, I believe. I used to believe and say that Deepin Team does not use Linux Deepin but since @hualet answered that they do, I have nothing else to say. It is impossible to miss this kind of issues if they'd be using it by themselves but, well, they say they do use. How did they miss these easily visible issues? I have no idea. 

Anyway,  I hope, they solve the issues in a short period of time. I still love Deepin since they move in a different path than other distros. I will keep supporting. Hopefully, they will not make any major mistake in the future.

**Comment by keybreak** [comment]
@gokhanyildirimlar 
This always starts from [small things](https://github.com/linuxdeepin/developer-center/issues/952)...
And leads to huge failures [one](https://github.com/linuxdeepin/developer-center/issues/1093) & [two](https://github.com/linuxdeepin/developer-center/issues/1121).

But enough is enough.
I've seen all thins bug for ages while testing kwin, like x20 times more than you just have reported, and we both could do this before release.

Nobody force people to actually BREAK what was working, or introducing raw unfinished features...

And i also understand your frustration with store, but luckily at least here i wasn't affected as i'm using Manjaro Deepin, which have everything in terms of software...

**Comment by gokhanyildirimlar** [comment]
> I really don't understand what cause people who already made such a beautiful DE in the first place, to make mistakes of that scale, especially if they use it themselves.
> 
> If it's not ready - don't release, if it's poorly tested and buggy - don't release.
> It's as simple as that.

Agreed @keybreak and actually, I don't know anyone who doesn't agree with this.

**Comment by ojoakua-10bit** [comment]
Blur background on Deepin Terminal also doesn't work on other mutter-based wm like mutter on gnome and muffin on cinnamon. Seems like the blur option only works on deepin-wm currently

**Comment by hualet** [comment]
I thank you all for the contribution you did and apologize for the rush of the release of 15.10, it's not my intention thro.

I still want to defend deepin devs a little bit on `It is impossible to miss this kind of issues if they'd be using it by themselves but, well, they say they do use. How did they miss these easily visible issues?`. 

deepin has ~200 projects on Github, but only got a few devs to develop and maintain them, I mean really a few. That's why I so badly want to make deepin a real developer community.

How did we miss these easily visible issues? because there're too many other things to do and to fix, see part of the closed issues during the development of 15.10: https://github.com/linuxdeepin/internal-discussion/milestone/7?closed=1.

Releasing KWin too early, bad strategy, I agree. But I just want you to know, it really hard to do this all in such a condition for us devs, I mean really hard.

**Comment by keybreak** [comment]
@hualet 
Like i've said, first of all i personally get that it's hard to maintain such a huge project - that's exactly why i was defending Deepin devs wherever i could and took a hit on Manjaro Deepin front myself to explain our current difficulties and quickfix ways to get around problems & manage to keep a lot on non-sense bug-reports away from your team so you could actually work on something; secondly i was one who hugely pushed kwin in the first place to fix a lot of known issues with nvidia, resize of windows, lags & quirks of settings etc.

But come on man, what's the rush to push raw bullshit?
It's not about how many packages & github projects you have, it's about simple logistics & technical process of NOT doing intentional mistakes and not breaking what's working.
It doesn't seem to me that you're Microsoft and on a payroll of huge corporations to rush (at least how you describe the team).

1. This is completely disrespectful to general user base & longtime contributors who want their experience and want it stable.

2. You've seriously f**cked things up about quality control, testing and general reliability of packages & DE overall for at least 3 months everything is constantly breaks on Arch / Manjaro / Little less on Deepin because you release only stable tags there.

3. There was **A LOT** of people who was willing to help you with deepin-kwin, but for example i know for a fact that myself and @antechdesigns was constantly bug reporting stuff before deepin-kwin even was a project and only very small fraction of our bugs have been fixed, and some of them actually got broken with newer releases. For example now i have 44 open issues. So it was let's say a bit demoralizing and pointless to help with something that's in alpha-beta phase, right? If only we could know that it will be released on stable in that state!!!

4. I personally could help you with testing deepin-kwin prior this public release, as i've said there are tons of bugs which is absolutely impossible to miss if you even use this OS / DE. But thought process was: "well i see that they constantly report & fix stuff in internal discussion (mind you i constantly read it, even that it's in chinese)...So even if i'll report tons of this obvious stuff i'll probably just annoy them with what they know, and seems like a lot of this will be fixed when it will be released to public" - **WRONG**!

5. If you think that it will pass by constantly letting people who support you down by: breaking designs, introducing new bugs without fixing old ones, constantly breaking with each update what was perfectly working before - **it will not** pass.

6. I have hold a lot of found bugs (outside the kwin) unreported for months, because i knew that you're working on kwin and this will do nobody good except interrupting, but in my worst nightmares i couldn't think that you would release **THIS**. So i could spend all my time now just crushing your upstream with bug-reports, some of which are pretty serious like basic operation type of serious. But really there's no point considering whole situation.

7. I really don't see any way to support & help team with such mentality. And also got me thinking how same people could build something that beautiful in very near past and fail to just maintain it in same state. Nobody would say a single word, if you would just silently make **deepin-kwin** up for your own standards right until it's perfect and wouldn't release broken stuff for months like you did. Nobody needs a new features which break what is working. Updates for sake of update - is for Microsoft and Apple, i really thought that you're better than that and understand this simple things, especially considering what you managed to achieve + publicity like [that](https://www.forbes.com/sites/jasonevangelho/2018/12/10/meet-the-linux-desktop-that-blows-away-windows-10-and-macos/#51ee9d6c5000)

**Comment by gokhanyildirimlar** [comment]
Deepin did a wrong move with rushing KWin without beta phase but there is nothing to do about it now other than trying to solve the issues quickly. I said people from the Turkish community also that they should open an issue if they find bugs, so, Team can unbend it like before. Hopefully, they'll do it if they find something or at least, they will let me know. It will be much better in the long run, I believe. I know that Deepin has such a small developer team but please, don't rush for anything. This is not good for Deepin's reputation. I'll keep supporting Deepin since I love the path Deepin team walks in. Other distros are mostly a copy of each other with the same feeling. 

Meanwhile, I can't open an issue for the AppStore because it's not a bug or a feature request but someone should really take care of it. Many people love that it contains proprietary software also. They don't go anywhere, they find what they need and just click install. Just like how they do on their phones... But no, everything is old and most of the previously available apps are unavailable. Let people feel comfortable with the AppStore and they will settle @hualet. This is, really, so important and is one of the things that distinguishes Deepin from others. Some people can install whatever they need to by finding packages or source code but some will just move to another distro. Don't let this happen and it will strengthen Deepin's hand in competition with other distros.

**Comment by BLumia** [comment]
Will look into the Deepin Terminal issue later, for the release policy issue, maybe we should start a new issue instead of this one since it's kinds of off-topic? Thanks!

**Comment by gokhanyildirimlar** [comment]
> Will look into the Deepin Terminal issue later, for the release policy issue, maybe we should start a new issue instead of this one since it's kinds of off-topic? Thanks!

Okay, this is not something critical. Okay, I open a new one with the same internals.

**Comment by gokhanyildirimlar** [comment]
I opened a new one, so, I close this.

**Comment by BLumia** [comment]
😅 Ah I means we should discuss the release policy issue in another issue instead of this one.

Lemme do this later :)

**Comment by gokhanyildirimlar** [comment]
@BLumia, sorry, I was kinda sleepy and I got you totally wrong there. :sweat_smile: Okay, that topic ended already, I guess. So, can you mark them as off-topic?

**Comment by BLumia** [comment]
Should be fixed in the next update :D

> Okay, that topic ended already, I guess. So, can you mark them as off-topic?

Well the discussion is fine. I'll just leave them as-is so we can reference it from other issue thread when needed :)
