### ISSUE TITLE
Directory shortcuts from secondary disk lose their icon after reboot.

### ISSUE THREAD

**Issue by gokhanyildirimlar** [linuxdeepin/developer-center#1189]
## Describe the bug
Directory shortcuts from secondary disk lose their icon after reboot. They gain their icon back after a renaming process. This doesn't happen with shortcuts from the system disk.

## To Reproduce
1. Send a shortcut of a directory from secondary disk to desktop.
2. Reboot the system.
3. You'll notice that the shortcut lost its icon.
4. Rename it and it'll gain its icon back.

## Expected behavior
Icons should stay after reboot.

## Video
http://sendvid.com/jrp8vggc

### Distro & Version
Linux Deepin 15.10.1(Fresh installation)

**Comment by BLumia** [comment]
Did your mountpoint of your secondary disk changed after reboot?

**Comment by gokhanyildirimlar** [comment]
> edit: whoops, seems not. but what about press F5 and check if the icon become normal?

It works @BLumia. I didn't know that I can refresh by pressing F5. They gain their icon again after pressing F5.

**Comment by BLumia** [comment]
It's because the symlinked folder is not existed when the desktop program started (the volume is not yet mounted at that moment).

Maybe create a `.desktop` file for that is a better idea since you can change it's icon then.

Closed, feel free to comment if you have any other related question :)

**Comment by keybreak** [comment]
@BLumia 
But if it happens to all symlinks on desktop after start, maybe it's worth to trigger some auto-update hook after boot so icons would get updated after mount?

**Comment by BLumia** [comment]
> But if it happens to all symlinks (from non system drives) on desktop after start, maybe it's worth to trigger some auto-update hook after boot/mount so icons would get updated after mount?

It's probably better if we use `.desktop` file as "shortcut" entries rather than symlinks. We are planned to add a shortcut creator util for that purpose which can also be used to create "shortcut" for executable files.

**Comment by keybreak** [comment]
Yeah, but in this case we're talking about just symlinks to directories, which would be weird to use desktop entries for

**Comment by BLumia** [comment]
> Yeah, but in this case we're talking about just symlinks to directories

It's not recommended for that case, think about there is a symlink pointed to a not existed location but you still have to check if the location become valid every few seconds/etc?

btw actually there was a auto-update timer inside dde-desktop but it got removed due to the lag of preformance. Single-shot timer is also not a good idea since you really don't know when that location become valid, inotify is also not a good idea for that case.

**Comment by keybreak** [comment]
No, of course auto-update periodical timer is not an option.

I was thinking about some sort of single action hook for successful mount, are you sure it's not possible?
I don't remember Linux Mint having this problem with icons from another disk symlinks, there must be some viable solution. Check some other DEs?

**Comment by BLumia** [comment]
> I don't remember Linux Mint having this problem with directory icons from another disk symlinks, there must be some viable solution. Check some other DEs?

AFAIK they both are not using symlinks.

> if any disk successfully mounted -> update desktop symlinks icons

This will also cause dde-desktop start a littlebit more slow since it will need load the (file manager) device controller.

Anyway I still think using symlink for that purpose is not a good idea. Other way like create a desktop entry via "send to desktop" (instead of create a symlink -- but you can still create symlink via "create link") can be better.
