### ISSUE TITLE
User Experience Program

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1261]
I think it's time to raise an alarm.

https://www.deepin.org/en/developer-community/planning/

    Add the switch - “Join User Experience Program” to make the user needs better understood.

By any accounts this can not be good.

No CEIP have ever done any good, except privacy violation and so on...
Windows 10, Ubuntu, Mac OS you name it.

> Even if we assume that this is all dandy and good, their settings have known to be working like s**t sometimes, and even if you opt out from some settings - sometimes it doesn't mean that you actually out (for example there was auto-login, sound problems like that).

@oberon-manjaro can you please speak to @BLumia about it, until it's too late?
Maybe having settings with this options and all related code cut off from Arch / Manjaro package or something...

____

Let's just say i'm really concerned about:
1. Privacy and any possibility of tracking, considering already not perfect reputation and rumors (even if they haven't been proven).

2. Stability of system & current amount bugs.

**DO NOT** MAKE THAT MISTAKE.
This will kill Deepin for a lot of people out there who could tolerate it for beauty, and that is exactly opposite of what we all need right now.

If you really want user experience program, bug-reports etc - use separate Deepin feedback program & extend it however you want, but please don't make this part of core functionality of system & settings. It is insane.

**Comment by Iiari** [comment]
Absolutely agreed this is not a good move.  If they want to wreck their own distro, so be it, but this option should be stripped out for other distros using the DE (Arch, Manjaro, Reborn, etc).

**Comment by ZhengshuaiPENG** [comment]
Please consider adding an individual app to collect user experience.

**Comment by damian101** [comment]
@ZhengshuaiPENG I think an extra package that manages the user experience program and can be uninstalled without problems should also do the job. 
The "Join User Experience Program" option should appear when the package is installed and hidden when not installed.
Other distributions could then just choose to not install the user experience program package by default.

**Comment by es20490446e** [comment]
I feel you all complain too much. You are behaving like micro-managers.

The Deepin team could do things better, but they are doing pretty well. They are being helpful even when dealing with other distros.

**Comment by BLumia** [comment]
I asked the related guy and for what I got is, the User Experience Program will not affact non-Deepin distro. That's all what I know, so please keep an eye on it :)

**Comment by keybreak** [comment]
@BLumia 
Thank you, i really hope so!

**Comment by zhuxiujuancindy** [comment]
The switch of user experience program can be turned off, and it is off by default in our design

**Comment by keybreak** [comment]
@zhuxiujuancindy 
That's definitely a good practice to turn off by default thx for info, but still:

> Even if we assume that this is all dandy and good, their settings have known to be working like s**t sometimes, and even if you opt out from some settings - sometimes it doesn't mean that you actually out (for example there was auto-login, sound problems like that).

There was known bugs like that associated with Deepin settings (i wish there was none, but sorry it's just current reality).

So still - far better option would be a separate package that can be just removed to ensure that it's really off (settings of course still can have this option for convenience, **if** package is installed).

**Comment by franklinnowell** [comment]
> The switch of user experience program can be turned off, and it is off by default in our design
Now that this feature is implemented, it's doing the exact opposite: It is ON BY DEFAULT and CANNOT BE TURNED OFF (please see https://github.com/linuxdeepin/developer-center/issues/1738).
It's a disaster!

**Comment by es20490446e** [comment]
After reading the [privacy policy](https://bucket.cdn.deepin.com/public/report/2020/04/30/22-18-26-a9da8673.txt) I shall change my position.

The wide range of collected info is potentially perfect for the Chinese government to perform [cyber warfare](https://en.wikipedia.org/wiki/Chinese_cyberwarfare). Making a perfect map of a targeted system, knowing at which times it would be more vulnerable, what window of time it has on a zero day exploit, and how likely it's the system to have a vulnerable software installed.

Since the feature is enabled by default, and re-enabled after upgrading to version 20, it means that Deepin collected the info for **all** their users at some point 🙈

Furthermore, many legislacions among the world require any data collection to be explicitly enabled by the user. Rendering the User Experience Program legality questionable.

We should add that the upgrade to Deepin 20 rendered a wide range of core features broken, including system freezes of all kind.

As result my assessment is that currently Deepin is far from being secure or functional. And everyone must stop using it till those are, not only disabled by default or mitigated, but **completely removed**.

**Comment by BLumia** [comment]
> Since the feature is enabled by default, and re-enabled after upgrading to version 20, it means that Deepin collected the info for **all** their users at some point 🙈

It's probably a bug according to https://github.com/linuxdeepin/developer-center/issues/1738#issuecomment-631466127 , hope they are working on a fix :/

**Comment by xmuli** [comment]
@franklinnowell @es20490446e，
As you can imagine, this feature should be turned off by default, but the inability to turn it off now is a very serious bug, at this moment the relevant developers have been informed, we will fix the problem as soon as possible. (Answer to the original question, already answered above at #1738;)

**Comment by felixonmars** [comment]
We apparently have a broken dde-control-center release and the underlying "deepin-user-experience-daemon" was not packaged or perhaps even open-sourced. So currently the switch is a no-op and should be hidden after further fix-ups.

**Comment by es20490446e** [comment]
Thinking better, I think that the underlying cause of these problems are expectations. That is Arch is always upgrading to experimental Deepin releases, when its developers never intended them to be daily drivers but just development previes.

So the real fix here is Arch only to upgrade to stable Deepin releases.

Deepin could also improve the situation by releasing its features in a one by one manner, instead of performing all together major upgrades.

But that isn't the cause of the broken desktop Arch experiences.

**Comment by felixonmars** [comment]
@es20490446e Like I said in a previous issue, most of the issues are present in stable releases as well if we don't catch them in the latest versions. The issues are a combination of different versions of system components, different paths, different expectation of user configurations etc, and you cannot expect them to fix themselves if we just bump to next "stable" version which basically means a bigger batch of upgrades at a time and helps none of the above.

**Comment by es20490446e** [comment]
@felixonmars Not true, sorry.

The packaged Deepin version isn't a beta, but a demo. Not adequate for early adopters, only for core developers.

And those desktop hangs, and missing functionalities, have nothing to do with dependencies. But with Deepin code itself.

The rapid development is missing [step number one](https://imgur.com/a/cwppF1C).

**Comment by es20490446e** [comment]
I'm not blaming anyone here. I'm just saying that **strategy** should change.

**Comment by es20490446e** [comment]
[Example](https://youtu.be/YQe7gi1Iur8) (requires VPN on China).

**Comment by meiyixiang** [comment]
62/2000 
The community currently blocks all user data collection activities and does not collect user data.
