### ISSUE TITLE
Is this Possible

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#1262]
@BLumia @felixonmars

I have an idea, I don't know how all this stuff works, so bear with me....

Is it possible to open a testing branch for deepin pkgs - arch, you know like with arch you can enable testing, in your `pacman.conf` file should you choose to test & report bugs.

Our production machines would be safe from buggy updates until the testers have given the all clear, no bugs etc. Then and only then would you release to the public. these bugs would have to be fixed anyway, they'd just be sitting in testing, until ready for release.

Its just an idea, save @felixonmars just uploading them after testing on his machine, at least this way they would have been tested on multiple machines, because clearly hes not seeing what some of us are seeing and hopefully remove some of the stress from him.

I have been racking my brains here (didn't take long) and this is the only thing I can come up with, I don't know if this is possible and I don't want to lose deepin but with whats happening at the moment, we ain't going to have a choice.

Thank you for you time & efforts ;)

**Comment by felixonmars** [comment]
This is possible. However we have some disagreement in the line between go / no go.

Arch's [testing] repo is hardly used to track small upstream bugs, and certainly we have some disagreement on what small is :/

If upstream always tags buggy releases (like doesn't build cleanly, won't run, crashes on main functionalities), the testing repos can be used to hold the updates for a bit. The Tester group, however, need to respond timely in Arch's signoff system. Currently this is only enforced for [core] and most testers only signoff [core] packages.

But IMHO for a new release with some bugs, like random crashing in the background (but does not affect usage most of the time), or new bug in one function (may not be the main purpose of the tool), it's not really a blocker for me. It happens on most software and upstream needs some time to fix their stuff.

I am saying this because, if we are going to hold new packages by a small bug, we can hardly update a package anymore as they are going to stuck in testing repos. Not to mention that combining different versions of DDE will result in even more bugs (as it's *more* unsupported) so I hardly do that.

But yes this can help with some problems like the deepin-screenshot doesn't even open one you mentioned. We still need someone to do the quickfix job, though. I sometimes managed to do that, but I failed very often when I get lost in the Qt plugin or WM etc.

**Comment by keybreak** [comment]
> This is possible. However we have some disagreement in the line between go / no go.

Well...Obviously not launching or crashing programs is blocker and no go.

But, for example if we were testing i would consider this kinds of bugs as blockers too (and wouldn't release this packages until they get fixed):
https://github.com/linuxdeepin/developer-center/issues/891
https://github.com/linuxdeepin/developer-center/issues/1200
https://github.com/linuxdeepin/developer-center/issues/1166
https://github.com/linuxdeepin/developer-center/issues/889

How about you, for this kinds of examples?
All of those will heavily influence any user's experience right away.

> The Tester group, however, need to respond timely in Arch's signoff system.

How timely exactly? 6 hours?

_________

> We still need someone to do the quickfix job, though. I sometimes managed to do that, but I failed very often when I get lost in the Qt plugin or WM etc.

That's the most important part, we need people except yourself who can actually fix / make pr and have enough experience to do this outside of Deepin team.

I've asked around Manjaro forum, so far not so much enthusiasm considering question of the day is to drop Manjaro Deepin or not...
Do you know anyone on Arch willing to volunteer to this kind of testing / fixing activities?

> I am saying this because, if we are going to hold new packages by a small bug, we can hardly update a package anymore as they are going to stuck in testing repos.

That's normal i guess, as payment for being more stable.

> Not to mention that combining different versions of DDE will result in even more bugs (as it's more unsupported) so I hardly do that.

Now that could be a real problem...So you're saying it's not really possible to hold for long enough, until something really heavy gets fixed?

_____

Another option would be to release only stable Deepin tags (follow only actual Linux Deepin release model), and spend more time on testing branch of Arch / fixing bugs.

**Comment by felixonmars** [comment]
> But, for example if we were testing i would consider this kinds of bugs as blockers too (and wouldn't release this packages until they get fixed):
> #891
> #1200
> #1166
> #889

It's in the middle, I can create a category like "I can wait a bit". So if someone is on that topic and a fix is expected to come within, say a few days, I can wait for a fix. But clearly that's not the case here.

> > The Tester group, however, need to respond timely in Arch's signoff system.
> 
> How timely exactly? 6 hours?

Within a week, that's the usual slower plan.

> Do you know anyone on Arch willing to volunteer to this kind of testing / fixing activities?

I don't think so. They would have been here already. 

> > I am saying this because, if we are going to hold new packages by a small bug, we can hardly update a package anymore as they are going to stuck in testing repos.
> 
> That's normal i guess, as payment for being more stable.

Not normal if it's going to be there for over a week. So if there's not already someone working on it or at least someone said he will, it has to be moved to stable repos or removed.

> > Not to mention that combining different versions of DDE will result in even more bugs (as it's more unsupported) so I hardly do that.
> 
> Now that could be a real problem...So you're saying it's not really possible to hold for long enough, until something really heavy gets fixed?

It's not really possible to wait for everything gets fixed. And since DDE components depend on each other very tight, holding a package would apply to the whole set of updates. It's not realistic to expect a perfect bug-free version of all DDE components. We often decide to stablize it or drop it within a week, and dropping happens very rarely (only with very serious un-fixable problems). Like I said above, it can be longer only if the problem is very likely to be fixed very soon.

> Another option would be to release only stable Deepin tags (follow only actual Linux Deepin release model), and spend more time on testing branch of Arch / fixing bugs.

IMHO that helps very little here. Most of the said problems are present in stable tags too. Things like different dependency versions, different configuration mechanism among distros, different paths are more of interest here. And also many problems are present in Deepin the distro as well.

**Comment by jonathonf** [comment]
> Another option would be to release only stable Deepin tags (follow only actual Linux Deepin release model)

If the git tags don't denote releases then they shouldn't be used as the basis for distribution packages. This goes back to https://github.com/linuxdeepin/developer-center/issues/1093.

**Comment by keybreak** [comment]
@felixonmars 
https://www.archlinux.org/packages/?sort=-last_update&q=deepin&maintainer=&flagged=

Seems you're using **Community-Testing** now, managed to find more testers / fixers on Arch?

**Comment by felixonmars** [comment]
@keybreak No, those are for the Qt 5.12.4 rebuild. Tester applications are open in case you are interested: https://wiki.archlinux.org/index.php/Arch_Testing_Team

**Comment by es20490446e** [comment]
You don't really need to hold updates to warrant quality. Instead a better approach is simply to fix what is broken before adding more changes, and testing what could be broken before committing changes.

I know this sounds overly simplistic, but it's like that. The problem isn't the lack of process, testing periods, or automated testing. The problem is simply not testing code just after having written it, and continuing coding more leaving leftovers all over the place.
