### ISSUE TITLE
Deepin Bug. DDE can't afford multiple opened windows or drag&drop!

### ISSUE THREAD

**Issue by Mark-AAAA** [linuxdeepin/developer-center#1337]
I don't know if this issue belong here, but I'm posting it and there is the need to move it I will move it.

For some reason, DDE can't afford multiple opened windows and the drag&drop function!
As you can see when you select one of the opened windows, an ghost layer of that application appears behind the visible window which cannot interact with the mouse but the ghost one can.
To solve this, I have to scroll up on the active application icon at the dock and then I select a window.
The same when you drag and drop a file. 

![deepin-screen-recorder_dde-desktop_20190624122252](https://user-images.githubusercontent.com/52075807/60342790-11ea1b80-99bb-11e9-9708-1b84d1525575.gif)

![deepin-screen-recorder_dde-file-manager_20190507180253](https://user-images.githubusercontent.com/52075807/60342915-6b524a80-99bb-11e9-9826-78f13e6ce5f1.gif)

**Comment by keybreak** [comment]
@BLumia 
You better be sure by now, because it's most hardcore bug which is apparrent in all dde versions, and it's not fixed for months:
https://github.com/linuxdeepin/developer-center/issues/1200

Specifically click part.

It happens for all programs, and it's super easy to see if you use dde at all )

**Comment by Mark-AAAA** [comment]
> Not sure but seems more likely a dde-file-manager bug. Will look into it later.

No, it is not dde-file-manager's bug, that was an example.
The same issue appears to be with every program.
It's a very critical and annoying bug.
![deepin-screen-recorder_dde-desktop_20190629163718](https://user-images.githubusercontent.com/52075807/60384955-95c00880-9a8c-11e9-8d8d-79876e48090f.gif)
![deepin-screen-recorder_dde-desktop_20190629163238](https://user-images.githubusercontent.com/52075807/60384956-95c00880-9a8c-11e9-84e4-9ca49bfeb6af.gif)
The same bug appears when you try to drag and drop a file.

As you can see at the pictures below, the deepin-screen-recorder detects the "ghost" layers.
![DeepinScreenshot_dde-desktop_20190629163709](https://user-images.githubusercontent.com/52075807/60384982-d750b380-9a8c-11e9-8024-cc7195746e15.png)
![DeepinScreenshot_20190629163656](https://user-images.githubusercontent.com/52075807/60384983-d7e94a00-9a8c-11e9-8447-b20f45134e02.png)
![deepin-screen-recorder_chromium_20190629164442](https://user-images.githubusercontent.com/52075807/60385026-6067ea80-9a8d-11e9-8f0f-d5c3b755dad8.gif)

**Comment by BLumia** [comment]
Well I cannot reproduce it with my working machine, seems more likely a deepin-wm bug.

> Also check hover on preview under kwin (including Linux Deepin)

Seems works fine on the development branch (master), I haven't test if the released version still have this issue. cc @liuwen123 

----------

@keybreak just please, do not blame me about bug resolve time, I cannot magicly fix all these bug just because I can code.

**Comment by aiamuzz** [comment]
> Well I cannot reproduce it with my working machine, seems more likely a deepin-wm bug.

@BLumia ... in your own words ... if you cannot reproduce it, you can't fix it magically ... what should be the way forward ???

are you even concerned that users are reporting issues and your team are unable to reproduce ... your responses don't seem to express any concern at all !!!

seems Deepin Team's response after the debian stable release is one of ... 'ostrich's head in sand' ... we can't reproduce it so no hurry ... no worry ... and users are left in their own peril !!!

> @keybreak just please, do not blame me about bug resolve time, I cannot magicly fix all these bug just because I can code.

@keybreak ... i think we all have to treat DDE and Deepin OS as an alpha version until it matures(seems all the stability of debian-unstable is literally non existence ... 

I too have this repeated issue on my clean ISO install of Deepin OS that it does not even fight a little stress(a simple saving a image(file save dialogue window ... or ... a large data being moved from one place to another ... or ... a vm in the process of waking from suspend or going to sleep ... or ... any other operation that freezes the system for a moment ... and when one tries to hit alt+tab to switch or click more than once when in its frozen state ... or hit the shortcut for workspace view or windows view just kills all open application with all data lost and prompts for a fresh login ... ... ...i have already raised a thread [here ](https://github.com/linuxdeepin/developer-center/issues/1318) on that issue but the team has chosen to ignore the thread ... so i guess they are not bothered.

@Mark-AAAA ... this ghosting issue reported by you i haven't encountered it honestly ...

@BLumia ... but nevertheless it does not mean its non happening ... and going by the response you and your team has been demonstrating ...

i don't see it being resolved any time soon ... just like my freeze-crash-logoff does not seem to have been looked into so far ... this issue of the ghost windows too will not be resolved anytime soon ... 

 There is another bug i frequently face right from the time i installed the debian stable(clean iso install) ... the dock keeps disappearing ever so often ... i haven't reported it because of 2 things ...

1. I can't reproduce it myself ...
2. given the teams stellar responses on issues they are not able to reproduce ... imagine what would be their response to an issue being reported which the affected user himself can't reproduce ...

so i have just learnt to live with this frequent dock crash and the whole system crashes ...
my way of dealing with these really annoying issues is hit the shortcut i have configure that will kill the dock and restart it ... and just login after the whole system crash ... and too bad i can't do anything about the unsaved data after such a crash 

**What would have been a more professional approach by the team would be to HIGHLY worried of those issues(more than the ones that you can reproduce) which the user is taking the pains to report here on github** ... which if i have to guess would 1 user in a 100 user who would go thru the trouble of doing it as the other 99 users may not even be aware or educated enough or patient enough or bothered enough to report it here or at the forum ... and going by the stellar responses of the team with regard to those few who take the time out(even if they are 1 in a hundred or a few hundred ... inspite of their good intentions of doing it which is to help improve the OS ... seem to be the lucky ones who are being meted with utmost hostility and rudeness by the team !!!

Way to go Team Deepin !!!

If you don't find a way to get to the bottom of such nagging and frequent issues by some other means ... deepin OS is bound to lose all its good will that it has earned until 15.9 ... your hostility is no longer welcoming to the 1 in a few hundred people who report issues here ... so the road ahead is pretty clear ... a dark one !!!

**Comment by aiamuzz** [comment]
a reality check ... have any third party put up a Deepin OS review(video or text) praising Deepin OSes latest 15.10 release of how its the greatest of Deepin experiences so far ?

I haven't come across it ... if the community has any links please do post ... i would like to read/view those reviews ... given the current attitude of the Deepin team ... for all we know Deepin 15.10 could really be the greatest of Deepin so far !!! and we may actually be a minority of the disgruntled users who best deserve rebukes from the team ... for all our tantrums !!!

**Comment by keybreak** [comment]
@BLumia 
I answered you in other issue. I can see this bug on deepin-wm with 100% reproduce rate on real hardware and vm, deepin-kwin still seems to have some other form of this bug (i can reproduce on all editions of Deepin - can show video if it helps)..

> @keybreak just please, do not blame me about bug resolve time, I cannot magicly fix all these bug just because I can code.

I don't, really i have no questions or blame to you at all about it after last conversation...
Deepin's working model is client oriented (plus i can imagine what kind of clients you can serve in China), so no blame here at all, once everything is cleared.

Believe me, from where i came from - i know what it's like.

It's a shame that things are this way, but at least when we're honest and transparent with each other - i have no problems with accepting reality.

I was just surprised you haven't seem to heard about this one at all - and this is very very apparent bug which everyone in community have seen on all machines, had multiple reports on deepin forums also, but my report was pretty detailed and in time when this bug just came about...

**Comment by aiamuzz** [comment]
> I don't, really i have no questions or blame to you at all about it after last conversation...
> Deepin's working model is client oriented (plus i can imagine what kind of clients you can serve in China), so no blame here at all, once everything is cleared.
> 
> Believe me, from where i came from - i know what it's like.

i would certainly like to know what is this model ... if anything it may clarify on what comes across as a hostile and rude response ... and could help understand the situation better !!! ... @keybreak ... FYI i am on telegram with the same username ... you can find me in the deepin chat room ... i am just baffled at how things have changed after 15.10 ... given the number of issues i have reported and enjoyed it i can no longer say that now ... i am an understanding guy provided things are made clear !!!

**Comment by keybreak** [comment]
@aiamuzz 
Well, if you read this https://github.com/linuxdeepin/developer-center/issues/1260 very closely and aside from emotions, specifically @BLumia here https://github.com/linuxdeepin/developer-center/issues/1260#issuecomment-497971095...I think you won't have a lot of questions either.

It's sad, but that's just how things are.

**Comment by BLumia** [comment]
> @BLumia
> I answered you in other issue. I still can see this bug (click part) on deepin-wm with 100% reproduce rate on real hardware and vm, deepin-kwin still seems to have some other form of this bug (i can reproduce on all editions of Deepin - can show video if it helps)..

Good to know that! Let's continue discussion on #1200 then, and feel free to create separate issue if you want to discuss on multiple issues since it can make issue tracking much more easy to do :)

--------------

> > @keybreak just please, do not blame me about bug resolve time, I cannot magicly fix all these bug just because I can code.
> 
> I don't, really i have no questions or blame to you at all about it after last conversation...
> Deepin's working model is client oriented (plus i can imagine what kind of clients you can serve in China), so no blame here at all, once everything is cleared.
> 
> Believe me, from where i came from - i know what it's like.
> 
> It's a shame that things are this way, but at least when we're honest and transparent with each other - i have no problems with accepting reality.

Thanks for understanding!

> I was just surprised you haven't seem to heard about this one at all - and this is very very apparent bug which everyone in community have seen on all machines, had multiple reports on deepin forums also, but my report was pretty detailed and in time when this bug just came about...

It's hard to say, my development enviroment is a little weird, I have no dde-desktop installed for example (make debugging much more easier), and since for the last month deepin slowed the release cycle for a little bit, packages on my machine (which is built from dev branch) may have more difference than the released packages, so I am not quite sure if a bug is solved in dev branch but do not have a release yet (expect the packages which I do maintained).

Anyway will looking into these issues later, and thanks again for the bug report!

**Comment by aiamuzz** [comment]
> Good idea, let me tell you a story. So the first step is let the boss hire two fulltime QA to working on this, whoops, we need money to pay for them, then we need customer pay us money, customer are sending new feature request or they won't pay to our boss so we then need to work on that no-sense feature request now. Then we found that mips and ARM port breaks, and then developers need extra work time to get bug fixed. After get everything works again, two developer leaved the development team due to the high work load, customer feels bad about the release delay and stop planning buying the product. Now what should we do? Oh of course we should get two person get unpaid to do QA for Deepin. Is that right?
> 
> Things are not that easy as you imaged, we both would like to do better, but is that really helpful to just complain about bug without information provided and yelling developer about new code brings new bug?
> 
> Here 3:00 AM now and it's of course not working time. I am not even a manager of Deepin, I just would like to become one of a bridge to help Deepin become more community-friendly and help community people make better use of DDE. I did these extra things completely voluntary without paying any extra cent to me and I think that is already all what I can do now. It is totally fine if you doesn't have time or energy to help Deepin community out, but what's the point yelling to others who would like to help the community out and treat them as a free-of-charge customer support guy? I did also feel very frustrated since it seems all what I've done seems doesn't helps at all. Maybe I should calm down for a few days, stop do volunteering on Deepin community and take a rest. Sorry about that.

is this what you were referring to @keybreak ... hmmmm !!!

@BLumia ... what should be the way forward ... I am no techie or coder ... i am just an enthusiastic and passionate user ... If anyone of you can create a step-by-step guide with the exact commands that will grab the required logs/info that will help identify the issues in bugs that are hard to reproduce both to the affected user as well as the deepin team ... i can see myself deligently posting logs to such bugs ... that is the extent i can lend a helping hand ... considering things are so bad with regard to staffing/investment at Deepin ... 

then I wonder how other linux OSes that have raced to the top ... especially the new one's ... elementary OS , mxLinux(i never heard of it and its already at the top in distrowatch, solus OS, zorin OS ... what's sad is all of them are not even half as good in their visual appeal ... does it mean all these are well funded projects much more than Deepin OS ?

Deepin OS would beat any of these in visual appeal ... everyday of the week and twice on a sunday ... yet they have raced to the top ... hmmmmm ... i feel sad for Deepin OS ... if what @BLumia is saying is true !!!

**Comment by keybreak** [comment]
@aiamuzz 
The way i see it, i think most of Linux world of free / open-source OS are having a lot of maintainers / coders / community help, which requires:
1. Set of very strict rules and guidelines for community, coders, designers, testers, contributors

2. Following general established rules / patterns of how things always were in Linux developer community (Deepin btw seems to break a lot of this, that's why all those design innovation came about, for example i've heard a lot of people in Manjaro complaining about Deepin not following GTK theming strictly, that why we still can't have proper Open / Save dialog in non-qt program on Arch / Manjaro).

3. Be 100% transparent and straight-forward in how things are running.

4. Solus / Zorin etc are relatively new too, but still have waaaay more to go to become stable. Deepin was very rapid, but truly good projects previously required ages to grow for being actually on top (like KDE for example).

_____

The other way around is either go full-on Microsoft style of not giving sh*t about users and only server commercial interests, or trying to sit on two chairs as Deepin is trying to balance now...

But current active dev-community base is way too little for such move :crying_cat_face: 

And the only good example of such tactics would be Red Hat / Fedora...But their developer base is huuuuuge, so they can actually afford such division between corporate and free community-driven project (which Fedora is also actually an active test base for super-stable corporate Red Hat and it makes sense).

**Comment by hbhgwtf** [comment]
This problem also appeared on my computer from version 15.10-15.10.2

**Comment by Mark-AAAA** [comment]
nobody cares, bye.

**Comment by RailRanger** [comment]
I wouldn't close this issue, I recall it affected Deepin 15.11 when I tried using the unstable repository. I have a feeling it might be related to the freedesktop packages. I noticed it happened after I ran updates to those packages. My memory is foggy so I could be wrong, but I would not be surprised if this affects v20.

**Comment by BLumia** [comment]
It's kinda rude but still would like to say, it's really hard to handle such a big project and process all existed rule *timely*, developer works really hard to continue development. Hoping into another DE is also okay and quite understandable if a bug caused usability issue and developer is not able to solve it in a short term, but it doesn't means nobody cares. Leaving such comment and close the issue is irresponsible and such behavior won't solve any actual problem but annoying developers and other community contributors.

**Comment by RailRanger** [comment]
> It's kinda rude but still would like to say, it's really hard to handle such a big project and process all existed rule _timely_, developer works really hard to continue development. Hopping into another DE is also okay and quite understandable if a bug caused usability issue and developer is not able to solve it in a short term, but it doesn't means nobody cares. Leaving such comment and close the issue is irresponsible and such behavior won't solve any actual problem but annoying developers and other community contributors.

We love the distro and your everyone's hard work. Try to take some of the user frustration as a complement for loving Deepin so much that want it perfect ;p

**Comment by SiamSami** [comment]
https://github.com/linuxdeepin/dde-dock/pull/280

Fixed and merged. Can anyone close it?

**Comment by xd003** [comment]
Its very much unfortunate to say that this issue exists even now on deepin beta 20 ,i dont get how a 1 yrs + old critical issue like this can be left unattended for so long
