### ISSUE TITLE
BUG ? ... "Always on Visible Workspace" setting

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#1391]
Hi,

I have freshly installed DeepinOS 15.10.2 and have been testing stuff one by one ... 

**Issue 1 :** 
I have configure a shortcut to enable the setting "Always on Visible Workspace" window menu setting ... This shortcut is no longer working on kwin !!!

#

**Issue 2**
When i enable this settings with the mouse ... i can see that its implementation is a little off ... the following screen recorder should give you an idea of what i mean be its implementation being off ...

![deepin-screen-recorder_google-chrome_20190715131521](https://user-images.githubusercontent.com/3283676/61201615-b4680580-a702-11e9-85b8-d334e0b0b0b4.gif)

turns out enabling this option is placing this window on all the workspaces increasing unnecessary clutter !!!

might need to be restored to the pre 15.10 stable state ... where it should just move the window to the active workspace rather than placing it on all workspaces.

Cheers.

**Comment by BLumia** [comment]
> I have configure a shortcut to enable the setting "Always on Visible Workspace" window menu setting

How did you do the config?

> turns out enabling this option is placing this window on all the workspaces increasing unnecessary clutter

That's what "Always on Visible Workspace" means (so it's not a bug). If you just would like to move the window to another workspace, use the move to left/right workspace menu, or drag the window to the new workspace in your <kbd>Meta+S</kbd> view.

--------

btw there are two thing I would like to point out, you don't need to use the `!!!` which like a kind of shooting to discribe your issue, just discribe the issue is okay, another one is just what you've seen in the issue template, if you have multiple issues, submit multiple issue instead of report all on them in a single issue. 

Thanks!

**Comment by aiamuzz** [comment]
> How did you do the config?
> 
> >

I think i used the dconf-editor(it still shows the shortcut in the editor) ... its a setting configured from the earlier version of DeepinOS ... could that be the reason why its not working ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
