### ISSUE TITLE
Control Center not hide and not works

### ISSUE THREAD

**Issue by SPFxDeveloper** [linuxdeepin/developer-center#1407]
Hi.

Use Deepin Desktop 15.10.2, I have the Dock configured to hide and show automatically, however, I have the following problem:

After about 20 minutes of working with Audacity the Dock remains transparent and Control Center no longer responds.

If you open the control center, it stays on the screen and can no longer be hidden. All the options are shown, but it no longer responds, because if you click on any option, it does not perform any action.

NOTE: I'm currently looking to migrate to Linux, but I'm still working on Windows 10. While Deepin has virtualized it with Hyper-V and assigned it 4 processors and 8Gb of RAM. My PC is HP EliteBook 840 G4 with 16GB of RAM.

**Comment by keybreak** [comment]
@BLumia 
I think i've seen this once myself, it was on Arch VM and happen in relation to https://github.com/linuxdeepin/developer-center/issues/945

1. Random **coredumps** of deepin-control-center happens independent of user actions (and a lot during 24/7 workload)
2. Usually either deepin-control-center relaunches very quickly or even unseen to users eye (just flickers once sometimes together with dock).
3. But in very rare cases if such coredump happens when control center opened - you can't close it usual way.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
