### ISSUE TITLE
Deepin file manager - switching themes now doesn't work until program reopen

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1422]
## Describe the bug
For both **deepin-wm** & **deepin-kwin** when you switch deepin file manager theme - it's not updated correctly live and requires reopen, before recent updates (month from now) it wasn't that way.

## Expected behavior
Back to the good old times - switch themes of deepin file manager live :)

## Screenshots
https://i.imgur.com/0RKZ0qR.mp4

### Distro & Version
All: Deepin / Arch / Manjaro

### Related package version
deepin-file-manager  1:4.8.8.1-1

@BLumia

**Comment by BLumia** [comment]
Will look into this issue later.

**Comment by RailRanger** [comment]
I also have this issue on Deepin 15.11 and Manjaro Deepin

**Comment by BLumia** [comment]
Weird, I cannot reproduce this issue on both my Deepin stable installation and my working machine.. What's the `qt5dxcb-plugin` and `dde-qt5integration` package version? Thanks.

**Comment by keybreak** [comment]
On Arch:
**deepin-qt5dxcb-plugin  1.2.5-1**
**deepin-qt5integration  0.3.12-3**

> And did you know which package upgrade breaks the old behavior?

No idea specifically, but about a month ago, somwhwere in cycle of previous major update.

I though it was obvious so haven't bother to report :laughing: 

> Weird, I cannot reproduce this issue on both my Deepin stable installation and my working machine.. 

Again, please release your dev version to public!!!
It's always very bug-free. compared to actual public :laughing: 
Maybe you should test on actual public version?

**Comment by BLumia** [comment]
> deepin-qt5dxcb-plugin 1.2.5-1

qt5dxcb-plugin 1.2.6 has been released few days ago, maybe wait for a few days for package maintainer update the package and then check if this issue still happens?

> Maybe you should test on actual public version?

Yes I did tested it on the public version and still cannot reproduce this issue, I'm still not sure what caused this issue.

> Again, please release your dev version to public!!!
> It's always very bug-free. compared to actual public

Actually no that case :joy:  The reason you see I say I cannot reproduce because once I can reproduce an issue I will try to fix it / assign related guys to fix it without saying any extra word, so you can see my say "cannot reproduce" when I really cannot reproduce an issue :stuck_out_tongue: 

But take it serously, lot's of issue requires specific enviroment and settings to reproduce, it's also quite normal if someone else cannot reproduce a specific issue due to the given info is not enough to reproduce the issue. Just let us know when anyone have more details to provide and we are always would like to fix it :)

<details>
<summary>off-topic: softwaregore gallery - some known bug in development enviroment</summary> 

![dock preview](https://user-images.githubusercontent.com/10095765/61616813-04634100-ac9c-11e9-9961-898d53a7e7ee.png)

![disk mount plugin](https://user-images.githubusercontent.com/10095765/61616890-383e6680-ac9c-11e9-8440-4d3995dff5d3.png)

</details>

**Comment by keybreak** [comment]
> qt5dxcb-plugin 1.2.6 has been released few days ago, maybe wait for a few days for package maintainer update the package and then check if this issue still happens?

Ok i will report back then :smile: 

> But take it serously, lot's of issue requires specific enviroment and settings to reproduce, it's also quite normal if someone else cannot reproduce a specific issue due to the given info is not enough to reproduce the issue. Just let us know when anyone have more details to provide and we are always would like to fix it :)

Oh i do take it very seriously man! :smile_cat: 
But typically i'm trying to as vanilla default experience to test as i could (which means, if in doubt - install clean VM from .iso and do full update), in that case it's most clinically clean case it could be, if i can reproduce something that clean...Than i pretty sure everyone can

**Comment by BLumia** [comment]
Yeah I have an (almost) clean VM for quick testing on my laptop (actually it's also used to develop [another project](https://github.com/BLumia/deepin-terminal-ng) in my spare time. The QA team also haven't report this issue so it's still very weird.

btw, if you got KDE systemsettings installed, try change the render backend and check if that can fix this issue? 

Waiting for any other info so we can start debugging :)

**Comment by keybreak** [comment]
> btw, if you got KDE systemsettings installed, try change the render backend and check if that can fix this issue?

Changed to XRender - same.
This Happens both on **deepin-wm** and **deepin-kwin** so it shouldn't be cause anyway.

**Comment by Mark-AAAA** [comment]
I confirm this issue x86_64 Linux 5.2.5-arch1-1-ARCH, Deepin 15.11.
Similar to https://github.com/linuxdeepin/developer-center/issues/1484

**Comment by BLumia** [comment]
More likely not a dde-file-manager specific bug :/

**Comment by keybreak** [comment]
@BLumia 
Also calculator

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
