### ISSUE TITLE
Deepin file manager's trash - black line

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1433]
## Describe the bug
There's black line in Deepin file manager's trash now.

## Expected behavior
Before there was no back line, i want perfection back! :smile_cat: 

## Screenshots
![image](https://user-images.githubusercontent.com/47599989/61595118-df1ef600-abfb-11e9-8210-52e037f1d82f.png)

### Distro & Version
All recent

### Related package version
deepin-file-manager 1:4.8.8.1-1

@BLumia

**Comment by Mark-AAAA** [comment]
I think is a scaling issue.
Like, this one: https://github.com/linuxdeepin/developer-center/issues/1352

**Comment by keybreak** [comment]
Doubt it, most likely just mistake in specifically deepin file manager...

**Comment by aiamuzz** [comment]
> Doubt it, most likely just mistake in specifically deepin file manager...

hmmmm ... not there on Linux Deepin ...

**Comment by BLumia** [comment]
Did you use screen scale greater than 1.0x ?

**Comment by Mark-AAAA** [comment]
x86_64 Linux 5.2.1-arch1-1-ARCH, Deepin 15.11, Deepin WM, it's ok.
![DeepinScreenshot_dde-desktop_20190722100910](https://user-images.githubusercontent.com/52075807/61613007-c862b880-ac68-11e9-9347-6d3ad00e1c5f.png)

Maybe this is artifact caused by scaling.Like this:
![DeepinScreenshot_dde-desktop_20190722101004](https://user-images.githubusercontent.com/52075807/61613092-08c23680-ac69-11e9-993c-db0231e659e4.png)

**Comment by keybreak** [comment]
> Did you use screen scale greater than 1.0x ?

No it's x1.0, but i see this on all scales and all of my 3 real machines (one of them is x2.0).

**Comment by BLumia** [comment]
Probably caused by Qt version? I haven't test this issue on Arch yet, will test it later.

**Comment by keybreak** [comment]
I don't know, looks to me like accidentally shifted  element in qt designer 1px to right...

Happens both on **deepin-wm** & **deepin-kwin**, versions of qt tested:
Manjaro: Qt 5.13.0
Arch: Qt 5.13.0
Linux Deepin: Not sure how to check it, but it's up to date 15.11

**Comment by BLumia** [comment]
> I don't know, looks to me like accidentally shifted element in qt designer 1px to right...
> 
> Happens both on **deepin-wm** & **deepin-kwin**, versions of qt tested:
> Manjaro: Qt 5.13.0
> Arch: Qt 5.13.0
> Linux Deepin: Not sure how to check it, but it's up to date 15.11

Under deepin it's 5.7.1 with some patch from Deepin. (`apt policy qt5-default`). Deepin apps doesn't use Qt designder btw (so you will not able to find any `.ui` file in the source repo).

btw, since you can reproduce this issue, could you try the following steps and check if the black line will disappear?

1. Click the search button twice (so the advanced search bar will appears).
2. Select multiple files and right click, then click "Rename" (so the batch rename bar will appears).
3. Hide them, and check if the black line disappeared.

**Comment by keybreak** [comment]
> Select multiple files and right click, then click "Rename" (so the batch rename bar will appears).

In trash when i do this there's no Rename option at all, so can't go further than this step

**Comment by BLumia** [comment]
> > Select multiple files and right click, then click "Rename" (so the batch rename bar will appears).
> 
> In trash when i do this there's no Rename option at all, so can't go further than this step

Oh sorry, I means do these action in other file view, and then you can switch back to trash view and check if the backline remains.

**Comment by keybreak** [comment]
Yes, it still appears

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
