### ISSUE TITLE
File manager: transparent file details text

### ISSUE THREAD

**Issue by RickStanley** [linuxdeepin/developer-center#1619]
## Describe the bug
Transparent text in file details on list view mode, in dark theme.

## To Reproduce
1. Open control center and select deepin-dark
2. Open Deepin File-Manager
3. From the right side of search bar select list view
4. See bug

## Expected behavior
It should be gray if I recall correctly from the last update.

## Screenshots
![image](https://user-images.githubusercontent.com/23178554/71380762-e7160400-25a6-11ea-898b-fbc6ffd48d1f.png)

### Distro & Version
Arch Linux (5.4.6-arch1-1) Deepin 15.11

### Related package version
dde-file-manager 1.8.2

**Comment by github-young** [comment]
Same on Manjaro (18.1.5) DDE (15.11).
dde-file-manager (1.8.2)
Only observed in dark theme.

Solution NEEDED!

**Comment by Lokke** [comment]
https://www.youtube.com/watch?v=5ANa5_v3IBA

**Comment by RickStanley** [comment]
Thinking of closing this, since no dev has addressed this issue and more problems have emerged from last updates. I don't see no overall updates about these issues.

Sadly, I'm changing to another Desktop Environment...

**Comment by BLumia** [comment]
Hi and to tell you the truth, since all devs from Deepin team are concentrate on next major release (V20) of all DDE apps, I'm afraid there is no devs from Deepin team will maintains the current release under non-Deepin (distro), the next release will probably released at March or April btw....

For this issue, I guess It's probably a DDE's QPA plugin issue, but I don't have time to dig in this issue although I really would like to help. Sorry about that :(

**Comment by RickStanley** [comment]
I see. Shame, I was really looking forward for some quick-fix, I would do it myself but I've got no time.

Well, thanks for the response anyways, I'll keep this open tho since there are people with the same problem.

**Comment by Lokke** [comment]
**fixed** in archlinux with package version 1:5.0.0-5
