### ISSUE TITLE
Arch Linux rendering issues (input forms, menu bar, settings, context menu)

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/developer-center#1629]
# Rendering issues

## Hardware & OS

![Neofetch screenshot](https://i.imgur.com/kmlksLp.png)

## Drivers

I followed [this guide](https://github.com/lutris/lutris/wiki/Installing-drivers#nvidia-1) to install my drivers.

```
$ pacman -Q nvidia nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader
nvidia 440.44-8
nvidia-utils 440.44-2
lib32-nvidia-utils 440.44-1
nvidia-settings 440.44-1
vulkan-icd-loader 1.1.130-1
lib32-vulkan-icd-loader 1.1.130-1
```

## Screenshots

![Authentication prompt](https://i.imgur.com/UNCiVhZ.png)

Alert with multiple rendered lines.

![Hovering over menu bar, transparency disabled](https://i.imgur.com/fcdl9Jw.jpg)

Vertical line without menu bar background color.

![Hovering over menu bar, transparency enabled](https://i.imgur.com/DrhSl7l.jpg)

Vertical, not blurred, line without menu bar background color.

![Hovering over icons in settings](https://i.imgur.com/JmJtFh7.jpg)

Horizontal, not blurred, line without menu bar background color.

![Context menu with a border similar to user-agent style button border](https://i.imgur.com/tblwHcI.jpg)

Context menu with a border similar to an user-agent style button border.

## Videos

https://imgur.com/a/8HgQjiV

Flickering menu bar when an updating action occurs (e.g. opening an application, opening or closing a group) and other factors, such as hovering.

https://imgur.com/a/BpYxnhK

Some sort of miscalculation.

**Comment by RickStanley** [comment]
I also have the context menu border issue.

![image](https://user-images.githubusercontent.com/23178554/71990425-b9b59100-3209-11ea-9c06-519dec4757bc.png)

This problem showed up after dde- package update some time ago, not sure which package.
It also came with this issue #1619 

OS: Arch Linux x86_64 
Host: Inspiron 5548 A10 
Kernel: 5.4.8-arch1-1 
Uptime: 56 mins 
Packages: 754 (pacman) 
Shell: zsh 5.7.1 
Resolution: 1366x768 
DE: Deepin 
WM: Mutter(DeepinGala) 
Theme: deepin-dark [GTK2/3] 
Icons: deepin-dark [GTK2/3] 
Terminal: deepin-terminal 
Terminal Font: Noto Sans Mono 10 
CPU: Intel i7-5500U (4) @ 3.000GHz 
GPU: Intel HD Graphics 5500 
GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 / 530 
Memory: 3682MiB / 11898MiB

**Comment by profran** [comment]
I don't know if this is related to a video driver or not because I don't have dedicated graphics as mentioned by @PublicByte and I also have the same context menu glitch pointed out by @RickStanley 

![image](https://user-images.githubusercontent.com/26902524/72187937-cee01a80-33d7-11ea-9e15-a2128def77ba.png)

I'm also unsure which package update caused the glitch to appear, since I have just noticed it after some full system upgrades. This is a list of all the recent deepin package updates that might be related

```
[2019-12-01T08:44:21-0300] [ALPM] upgraded deepin-anything-arch (5.0.1-26 -> 5.0.1-27)
[2019-12-03T19:06:44-0300] [ALPM] upgraded deepin-anything-arch (5.0.1-27 -> 5.0.1-29)
[2019-12-09T18:26:48-0300] [ALPM] upgraded deepin-anything-arch (5.0.1-29 -> 5.0.1-30)
[2019-12-28T22:37:05-0300] [ALPM] upgraded deepin-anything-arch (5.0.1-30 -> 5.0.1-36)
[2019-12-28T22:37:06-0300] [ALPM] upgraded deepin-cogl (1.22.5-2 -> 1.22.5-3)
[2019-12-28T22:37:06-0300] [ALPM] upgraded deepin-qt-dbus-factory (5.0.1-3 -> 5.0.1-4)
[2019-12-28T22:37:07-0300] [ALPM] upgraded deepin-qt5dxcb-plugin (5.0.1-3 -> 5.0.1-4)
[2019-12-28T22:37:07-0300] [ALPM] upgraded deepin-qt5integration (5.0.0-4 -> 5.0.0-6)
[2019-12-28T22:37:12-0300] [ALPM] upgraded deepin-file-manager (1:5.0.0-3 -> 1:5.0.0-4)
[2019-12-28T22:37:12-0300] [ALPM] upgraded deepin-dock (5.0.0-3 -> 5.0.0-4)
[2020-01-04T17:43:20-0300] [ALPM] upgraded deepin-anything-arch (5.0.1-36 -> 5.0.1-37)
[2020-01-10T16:43:45-0300] [ALPM] upgraded deepin-anything-arch (5.0.1-37 -> 5.0.1-39)
```

This is my system info:

OS: Arch Linux x86_64 
Host: ThinkPad T440p 
Kernel: 5.4.7-arch1-1 
Uptime: 4 days, 7 hours, 57 mins 
Packages: 1136 (pacman) 
Shell: zsh 5.7.1 
Resolution: 1920x1080 
DE: Deepin 
WM: Mutter(DeepinGala) 
Theme: macOS-Dark-5.1-dark [GTK2/3]
Icons: deepin-dark [GTK2/3] 
Terminal: deepin-terminal 
Terminal Font: Droid Sans Mono 11 
CPU: Intel i7-4700MQ (8) @ 3.400GHz
GPU: Intel 4th Gen Core Processor 
Memory: 3739MiB / 7865MiB

**Comment by Lokke** [comment]
seems to be fixed in the latest packages 
![DeepinScreenshot_select-area_20200203004634](https://user-images.githubusercontent.com/6406275/73617448-1e081c80-461f-11ea-8286-8551469220f4.png)
![DeepinScreenshot_select-area_20200203004701](https://user-images.githubusercontent.com/6406275/73617449-1e081c80-461f-11ea-9daa-80b78f807c6f.png)

**Comment by LarsKoelpin** [comment]
I'm still experiencing rendering issues when hovering over buttons on arch

![image](https://user-images.githubusercontent.com/8105746/73876725-c43e6700-4857-11ea-8f73-3bc0631fa0ab.png)

![image](https://user-images.githubusercontent.com/8105746/73876811-e89a4380-4857-11ea-885e-28535946a17a.png)

Can confirm the context menu is fine now tho

**Comment by justforlxz** [comment]
Sorry for not replying for a long time, we are no longer dealing with v15 issues, thank you.
