### ISSUE TITLE
White border on the desktop when using Kwin

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1637]
When using Kwin, the desktop shows a white border on its right and lower edge, see the [screen-shot](https://i.imgur.com/KwOPWrB.png).

I guess this is because on Kwin the usable area of the screen is reduced one pixel, so no element can fully leave the visible screen. So the fix would be to draw the desktop background one pixel further.

Using Kwin instead of Mutter is interesting because the desktop is more responsive.

**Comment by BLumia** [comment]
If I remember correctly it's more likely a `dde-desktop` issue  and already fixed in the V20 codebase (https://github.com/linuxdeepin/dde-file-manager/commit/526c9b16fa92a16edcb73be4d4955b1b63ccb971). Since V20 release still need a lot of work to go so maybe you guys can try apply this patch to current released version and see if that can fix this issue.

**Comment by es20490446e** [comment]
That's interesting, although I think nobody at this time would be interested on applying this patch on my distribution. As they have even removed Deepin from being an officially supported desktop because all the bugs and trouble they had packaging it.

So I guess it would be better just to wait. Thanks and have a nice day.
