### ISSUE TITLE
Support for AMD Ryzen 7 3750H  and Nvidia GeForce GTX 1650 Max-Q 4 GB

### ISSUE THREAD

**Issue by Maxximo88** [linuxdeepin/developer-center#1712]
Describe the bug
No support for AMD Ryzen 7 3750H and Nvidia GeForce GTX 1650

## To Reproduce
I can provide Deepin User Feedback, or you can see my github page: https://github.com/Maxximo88/HP-Pavilion-15-ec0012nl

Graphics:
Device-1: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] driver: nvidia v: 440.82
Device-2: AMD Picasso driver: amdgpu v: kernel Display: x11 server: X.Org 1.20.4 driver: amdgpu,ati unloaded: fbdev,modesetting,nouveau,nvidia,vesa resolution: 1920x1080~60Hz OpenGL: renderer: AMD RAVEN (DRM 3.33.0 5.3.0-3-amd64 LLVM 7.0.1)
v: 4.5 Mesa 19.2.6

## Enviroments:
Deepin v20 Beta

### Distro & Version
Deepin v20 Beta

### Related package version
Deepin Graphic Driver Manager
AMDGPU
nvidia-prime

### Additional context
Gaming laptop

**Comment by Dziban-dev** [comment]
Ryzen 3000 for laptops use Zen+ architecture , which is supported by the linux kernel since 4.10 i belive, and Zen2 is supported since 4.21. Deepin v20 uses 5.3 which means your CPU should be supported from the getgo. someone correct me if im wrong.  the problem might be related with the manufacturer of the laptop, you see, laptops especially raven have boot issues with Linux depending on manufacturers, Acer for example didn't care at all and need additional parameters to boot. even latest kernel can't really help with raven.

**Comment by Zeno-sole** [comment]
What exactly is the phenomenon that cannot be installed?

**Comment by Zeno-sole** [comment]
Please try using deepin 20.3
