### ISSUE TITLE
Deepin Hotcorners not part of the Deepin V20.

### ISSUE THREAD

**Issue by lsatenstein** [linuxdeepin/developer-center#1714]
## Describe the bug

With deepin 15.x we have programmable hot corners. These have disappeared from V20.x

## Expected behaviour

Hot corners to be present as they are in version 15.

### Distro & Version

Linux Deepn 20.x Beta of 3 May 2020
### Additional context

The programmable hot corners and the menu along side the graphical view are what makes Deepin a desireable distribution. Without these programmable hot corners (not present), in the new V20, then I believe that Deepin is less functional than any comparable distribution built with gnome 3.36.1.  Users will be most happy to obtain Deepin 15. without the system settings along the right margin. 
Deepin demos on youtube can bring importance and even investment to your brand.

**Comment by es20490446e** [comment]
The thing is that previous existing hot corners are kept like they were, and now there's no way to modify or disable them.

**Comment by xmuli** [comment]
It's still being negotiated, and it's possible that later programmable hot corners will return to the new version, including some other old features.

**Comment by fernando2amigos** [comment]
That right bar with direct access to settings was THE feature.
I need to turn on/off my VPN quite often because of my job or switch from headphones to general audio output and now it's really hard and clunky to get to those setting via the panel. 
Even, in gnome they can be reached by typing the name and getting the matching results but not in DDE.
It's heartbreaking for me. 💔

**Comment by es20490446e** [comment]
@fernando2amigos Use KDE Plasma. You can configure it to look as Deepen was.
