### ISSUE TITLE
Deepin 20 Usability Report

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1726]
https://youtu.be/gNQTFG4oH_c

**Comment by xmuli** [comment]
In issues perhaps this kind of quiz video is difficult to get feedback and communication, try to go to BBS or TG; you will get more feedback and communication

 https://bbs.deepin.org/


PS: Due to the internet, it is possible that part of the country may not have access to this link, a small suggestion that can be synchronized and uploaded to https://www.bilibili.com/.

But thank you so much for the feedback.
