### ISSUE TITLE
[20 BETA] Focus after opening Guake

### ISSUE THREAD

**Issue by atar-axis** [linuxdeepin/developer-center#1731]
## Describe the bug
When you type something in guake console and if you try to write something in the searchbar of deepin, it doesn't work without clicking onto "search"

## To Reproduce
1. Install guake
2. Set Guake preferences to "hide on focus loss"
3. open guake and write something
4. Directly click on the start button and type something, nothing happens

## Screenshots
![Screen Capture_dde-desktop_20200514194143](https://user-images.githubusercontent.com/11148588/81967808-c57fec80-961b-11ea-8d65-b816f11af86c.gif)

### Distro & Version
Linux Deepin 20 Beta

**Comment by sayoojsamuel** [comment]
Hey @atar-axis, 
You could use deepin-terminal itself instead of Guake. Add `deepin-terminal -q` as a custom shortcut in your control center.  This should fix your problem.  

![image](https://user-images.githubusercontent.com/31436104/83166136-161f3b80-a12c-11ea-8c16-53fd1c8c3224.png)

You can further change quake terminal's configure at: `~/.config/deepin/deepin-terminal/config.conf`.
Readme: https://github.com/linuxdeepin/deepin-terminal/blob/master/README.md

**Comment by xmuli** [comment]
Hi, I just tried it with uos20 and deepin latest version, and it didn't reproduce your problem.
![截图录屏_VirtualBox Machine_20200611143509](https://user-images.githubusercontent.com/33887845/84354622-c775a500-abf3-11ea-9add-60e739b52c7b.gif)

**Comment by atar-axis** [comment]
> Hi, I just tried it with uos20 and deepin latest version, and it didn't reproduce your problem.
> ![截图录屏_VirtualBox Machine_20200611143509](https://user-images.githubusercontent.com/33887845/84354622-c775a500-abf3-11ea-9add-60e739b52c7b.gif)

I am not sure if this is really the same. You need to click in quake terminal and after that, in the efficient mode, open the main menu and press something without clicking in the search bar

**Comment by xmuli** [comment]
Here's what I did, because on 2020-06-04 deepin had an update:

```bash
sudo apt update
sudo apt dist-upgrade
reboot

sudo apt update
sudo apt install guake
````

Then start Guake in de-launcher, and press the F12 shortcut key; then can be entered directly into the string; then the gif result is obtained.

You can try it out, and you can try out our[ new terminals](https://github.com/linuxdeepin/deepin-terminal-reborn) and our [old terminals](https://github.com/linuxdeepin/deepin-terminal) (also with Thor's Beat Effect)
