### ISSUE TITLE
dde-dock 點擊右鍵會卡死

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/developer-center#177]
鎖定畫面後並解鎖畫面，在 dde-dock 的捷徑點擊右鍵會卡死

**Comment by sbwtw** [comment]
必现？步骤？环境？

**Comment by hugeblank** [comment]
(bless the internet and google translate)
I'm having this issue as well. Basically the entire dock takes ages to load, and when it does it's extremely slow at times, and fine at others. Overall just annoying to use. 
I get error messages mentioning negative sizes when I kill it and start it again using sudo.
 Corners and everything else work perfectly fine, it's just the dock that is a major issue.

**Comment by JulianLai** [comment]
終於被我發現關鍵了，在鎖定畫面後回到桌面會發生這現象

**Comment by sbwtw** [comment]
@JulianLai 我在 deepin 上测试了是没有问题的，可以发一下 gdb 的结果吗

**Comment by JulianLai** [comment]
@sbwtw 怎麼弄呢？

**Comment by JulianLai** [comment]
@sbwtw 看來不是鎖定畫面造成的，試了一下又沒發生了

**Comment by JulianLai** [comment]
@sbwtw 是這個嗎？
我無法複製訊息，因為 dock 卡住的時候這個 terminal 也會卡住
![p_20170221_144327](https://cloud.githubusercontent.com/assets/20014762/23153577/5b2fce68-f844-11e6-85ae-2cd522300c0a.jpg)

**Comment by sbwtw** [comment]
@hualet

**Comment by hualet** [comment]
新版本的deepin-menu会修复这个问题；
A new version of deepin-menu will fix this issue.

**Comment by hugeblank** [comment]
O.o I see something totally different from the image above. 

This is when I use `sudo dde-dock`
![image](https://cloud.githubusercontent.com/assets/16393543/23197260/05a14e4a-f8b7-11e6-9702-38e23b738e9d.png)

This is when I use `dde-dock` without sudo
![image](https://cloud.githubusercontent.com/assets/16393543/23197319/5b080a5e-f8b7-11e6-9d0a-348789382490.png)

Is this a totally different issue, am I doing something wrong? Should I open up a new issue?

It may be useful to see exactly what is on my dock for the following list, so I put a screenshot of that here:
![image](https://cloud.githubusercontent.com/assets/16393543/23197612/704e3db4-f8b9-11e6-8cd6-48dfaf9c51fd.png)

Here are the evident problems I see (other than the error messages above):

-The dock takes a long time to properly load, and update with icons when I open an application. 

-Hovering over the applications in the dock sometimes work, and sometimes does not. (partly having to do with the problem after this one, and partly because the dock takes a ridiculously long time to load.)

-The dock when not completely frozen and partly usable will work until I hover over the 'shut down' icon, and only with that icon it will freeze. After a while it will start working again. 

-Right clicking on the anything to the right of the shutdown button on the dock is a bad idea. Similar to the shutdown button, it freezes. But after a while it unfreezes and gives this error message: 
![image](https://cloud.githubusercontent.com/assets/16393543/23197540/e8f641c2-f8b8-11e6-9aa1-8b0a4ba8c2c6.png)

Apologies for giving everyone here a hard time by speaking a foreign language, and I hope that someone here can be an intermediate between me and the devs. 
Would it at all help if I used google translate?

  Cheers,
    ~huge

**Comment by hualet** [comment]
@hugeblank It seems to be a different issue, so please open a new issue.

DO NOT run dde-dock with sudo, it's totally not tested as dde-dock's not supposed to be run as root.

**Comment by sbwtw** [comment]
@JulianLai 应该没有问题了
