### ISSUE TITLE
Make more Deepin programs available to Archlinux

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1790]
There are a number of Deepin programs that are available for Deepin v20 beta but not for Archlinux yet.

It would be great if they were available for Archlinux as well.

**Comment by felixonmars** [comment]
I agree. Unfortunately the programs are quite troublesome so I have to do this slowly, as I have to patch every one of them to get them running properly.

For example 2 days ago I added deepin-voice-note to Arch and wrote two patches for its basic functionality to work:
https://github.com/linuxdeepin/deepin-voice-note/pull/1
https://github.com/linuxdeepin/deepin-voice-note/pull/2

Since they are currently so slow on merging patches I have to rebase and update my patches regularly, which kills even more time.

**Comment by xmuli** [comment]
Rear Accelerated Merge Patch 😱😱

**Comment by justforlxz** [comment]
is it finished?

**Comment by felixonmars** [comment]
> is it finished?

No. At least deepin-log-viewer and deepin-devicemanager are still in TODO.

**Comment by tsic404** [comment]
is it finished?

**Comment by tsic404** [comment]
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue
