### ISSUE TITLE
Stuck on shutdown

### ISSUE THREAD

**Issue by darkcyber** [linuxdeepin/developer-center#191]
Hi,

Sometime I have problem on shutdown in Deepin 15.4 Beta, that is stuck. Stuck at deepin logo shutdown exactly.

What cause this? Is this mean stuck because there is many process open and deepin is still killing it.

But I have this issue few time ago with Ubuntu 16.10, and I solve it with upgrade to latest stable linux kernel from kernel.org.

So can I upgrade to latest stable linux kernel from kernel.org in deepin 15.4 Beta ?

Or How I can fix this issue?

Thanks in advance.

**Comment by justforlxz** [comment]
This question has not been answered for too long and will be closed. If there is a need to continue the discussion, it will be reopened.

**Comment by snjvm** [comment]
After 20.5 upgrade multiple other issues have started. Reopening this thread for Shutdown is failing.
1. Shutdown is not happening.
2. Have to force press the Power to stop the system.
3. Have to get into BIOS to restart the system every-time.
4. Fear of losing the HDD because of forced power down.

![image](https://user-images.githubusercontent.com/62160616/163835438-3834b91c-df78-40a4-b564-f7f9a0345c8b.png)
![image](https://user-images.githubusercontent.com/62160616/163835479-032c7c26-5f05-4de3-ac27-3fe5552ca913.png)
![image](https://user-images.githubusercontent.com/62160616/163835504-6cdf4b81-f76b-4421-9056-cb081f6ada36.png)
![image](https://user-images.githubusercontent.com/62160616/163835538-409d6ae2-5a0c-4c87-b64e-0827bea08e76.png)
