### ISSUE TITLE
Write commit with Chinese?

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/developer-center#1914]
I see you write all commits with Chinese language, I don't understand why you do this, do you wanna reject all international developers?

**Comment by xmuli** [comment]
No, just because most of the developers are Chinese, and some of them have weak English. Considering that it has been practical, so there is priority in Chinese (in fact, there is no explicit stipulation that English or Chinese must be used for submission, so now Chinese and English are mixed), but some people have always insisted on using English (they are lighthouses)

**Comment by nanoant** [comment]
Deepin is IMHO the best looking Linux desktop environment and it has such a great potential to be the most popular desktop environment worldwide, better than GNOME and KDE. I understand and respect your decision to accept both English and Chinese in commit and source code comments. Unfortunately this decision as @hillwoodroc said effectively excludes all non-Chinese speaking developers from contributing to the project. Therefore it would be great if this could be revised in the future.

**Comment by zccrs** [comment]
We want to make changes for this, and the following rules are currently planning:
1. In the developer-center project, deepin internal personnel are unified in English to create Issues
2. For other personnel, we recommand the use of English to create Issues, but not forbidden to use Chinese. If this Issue is created in Chinese, then we will also use Chinese to reply him.
3. Prohibit language other than English and Chinese in Issues
4. For the document contents (such as readme file), the content of both English and Chinese languages
