### ISSUE TITLE
[BUG] File manager shows snap as drive (sqashfs)

### ISSUE THREAD

**Issue by vishnu-dev** [linuxdeepin/developer-center#1922]
### Issue
Whenever we install a snap using the terminal from https://snapcraft.io/, the application folder appears as a SQUASHFS drive in DDE File Manager which causes it to be cluttered.

### Screenshot
![image](https://user-images.githubusercontent.com/21088161/93711298-ca751f80-fb6a-11ea-82ce-4fbed67e5422.png)

### Expectation
The File manager should ideally show only the EXT4 and NTFS file system drives.

**Comment by peeweep** [comment]
This problem has been fixed in the latest version of Deepin (20.3) , if you still have problems, you can reopen this issue

![image](https://user-images.githubusercontent.com/624223/147644514-82d39bfd-c44d-4f0c-ba82-246cee364bcc.png)
![image](https://user-images.githubusercontent.com/624223/147644673-c3cdb523-466a-41f2-81be-da61698c33ca.png)
