### ISSUE TITLE
Rounded corner slider bar setting lost after reboot

### ISSUE THREAD

**Issue by forsback** [linuxdeepin/developer-center#1973]
It would be nice if you could fix the rounded corner desktop window setting so that it is not lost after a reboot. It defaults to max rounded corners. Setting seems to be applicable for Qt applications, not GTK. But this is a different topic.

(deepin-desktop-community-1002-amd64.iso, clean install)

**Comment by aiamuzz** [comment]
> It would be nice if you could fix the rounded corner setting so that it is not lost after a reboot. It defaults to max rounded corners.
> (deepin-desktop-community-1002-amd64.iso, clean install)

@forsback ... 
what rounded corner setting are you talking about ?

**Comment by forsback** [comment]
Please find the image attached. I have tried to use the rounded corner window control to get closer to GTK (Firefox) window rounded corner look. Setting is lost after reboot. It also does not affect GTK applications, seems to be working only for Qt based. But this could be a bigger issue. 

![Screen Capture_select-area_20201116142914](https://user-images.githubusercontent.com/47720296/99252903-6c865080-2818-11eb-822b-479d705d0494.png)

**Comment by aiamuzz** [comment]
thanks ... @forsback ...

I **WAS** a big fan of Deepin(the older Classic ... pre V20 version ... the side control panel, hot corner settings, central dock) ... i did install the new V20 on my system alongside the older version but never used it for the disappointment the radical changes V20 brings to the table ... 

thanks for your post(this issue) that spoke of controlling the **UGLY** rounded corners(of the windows and the dock) is when i booted into the V20 install i had abandoned ... after running the updates i did find the setting ... **MAY BE** i'll use the V20 with a broken heart ...



> It also does not affect GTK applications

What do you mean by this ... does it mean the GTK applications still bear the **UGLY** rounded corners ?



> Setting is lost after reboot

well i am sure it will be a momentary issue will get fixed in due course ...

**Comment by justforlxz** [comment]
After my test it works fine now. If you still have problems, please recreate the issue.
