### ISSUE TITLE
Deepin 20.2 partition size limited to 20GB

### ISSUE THREAD

**Issue by bh013** [linuxdeepin/developer-center#2066]
I have deepin20.1 installed on my machine, it used 6.5GB disk space
while i decide to new version 20.2 latest available version 
**installer limited user to have minimum 20GB forcely** 
while my SSD device have 16GB disk space 
 
i install it on virtual machine and a full installation used **6.2GB** only !
 
Why you force users to have a never used free space ? 
Why you force some users to stay on old versions ?
 
while it is possible to remove limitation completely, then installation may fail if disk space was not enough

**Comment by lxwndr** [comment]
The deepin has always had these limitations. In version 15, 15gb of available space was needed; while the new version (deepin 20) requires 20gb of available space.

Really, all these versions of deepin do not occupy more than 10gb.

deepin 20.2:
![Capturar_select-area_20210405110550](https://user-images.githubusercontent.com/45263160/113582570-e750dc00-95fe-11eb-8182-aaf33fb3d6bf.png)

**Comment by justforlxz** [comment]
Think about it, if the system only needs 6G space, and you only have 6G, how do you install the software?

**Comment by bh013** [comment]
@lxwndr This is not a right way to force users have a space that will never use, while 10GB is enough
 
@derekdai i install my software on another partition (all peoples no need to install big softwares) 
installer may can warn about this to user, **not force all users and prevent installation !** 
Your words are like saying "All peoples should install 14GB softwares, after os installation"
 
I have 12GB ram, Then i do not need shm/swap partitions too 
I want a clean OS to use SublimeText for coding only

**Comment by justforlxz** [comment]
> @lxwndr This is not a right way to force users have a space that will never use, while 10GB is enough
> 
> @justforlxz i install my software on another partition (all peoples no need to install big softwares)
> installer may can warn about this to user, **not force all users and prevent installation !**
> Your words are like saying "All peoples should install 14GB softwares, after os installation"
> 
> I have 12GB ram, Then i do not need shm/swap partitions too
> I want a clean OS to use SublimeText for coding only

My laptop has 16G of RAM and 1T of SSD. My machine is a small number of deepin users, and more users are still using 8G+256, or 4+128.

We know that we will not be able to satisfy all users, but we need to ensure that the vast majority of users can use this system normally. 

We are not KISS. According to feedback, many users have reported that the root partition is too small, which makes it impossible to install software and use it normally.

Although we know that there should be no restrictions, we need to consider extreme situations instead of throwing the problem to the user and complaining that the user does not consider their actual situation.

I personally think that if you plan to experience this system, 20G is not something that you cannot afford. If you plan to use it for a long time, then you should not only use the space below 20G.

**Comment by AcidRain9** [comment]
> Think about it, if the system only needs 6G space, and you only have 6G, how do you install the software?

Yeah I get your point

**Comment by bh013** [comment]
Yes, you are right
I think users should have minimum 240GB free space 
because of they may need to download a lot of videos 
( i will migrate to [ZorinOS](https://zorinos.com/) )
