### ISSUE TITLE
Errors and crashes after installation of Deepin V20.2

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2070]
Hello Mr. President of Wuhan Deepin Technology Co.,Ltd.

Attached are some details about installation and observations of Distro Deepin V20.2.

Thank you for the attention that is never given in Deepin Fórum.

Sincerely

Edson Santos 

[Instalaçao Deepin V20.2 II Ingles.pdf](https://github.com/linuxdeepin/developer-center/files/6275028/Instalacao.Deepin.V20.2.II.Ingles.pdf)

**Comment by yxsos** [comment]
hi. I am very happy to receive your suggestions, we will make improvements in later versions

**Comment by BLumia** [comment]
Thanks for the long issue report.

I believe some of the issue mentioned in your document already get resolved in the later updates (now we are on deepin v20.5). I suggest you try the latest version and see if the issues are addressed.

Since your document lists a lots of issues that make bug tracking much harder, I'll pick some of them to answer. If my answer doesn't cover all the issues you have, please create a standalone issue for each individual bug so we can track these different bugs in different issue threads.

> Couldn't they have fixed the ISO first and released this Deepin V20.2 version later? Why release it with problems to the users?

We do have QA to control our releasing quality, but we still cannot guarantee there is no bug in the final release. Some issues happen in some special condition that we didn't even know about, if there is known bug that will cause critical issue to the end user, we won't make a release. So that's why bug report is for, to let developers know there is a problem we may need to pay attention to.

> but the LOG generated can not be saved at the time of installation

We added a way to save error log in our installer, hope that could solve the problem.

> The information was filled in as requested and at startup a lock appeared after the UOS image, On this lock screen I had to enter the password, 

You opted for full disk encryption, so there will be a prompt to allow you enter password to continue (or the OS won't be able to load since the OS related files are encrypted, that's why you need a password at this stage). It's normal. Consider removing the full disk encryption if you just want a regular lock screen password prompt.

> the UOS image

Just FYI. UOS is not our community product, nor does it get our support from the community team. If the community ISO contains UOS image then there is something wrong with the ISO. Consider trying v20.5 and see if that still happens, and please create a bug report if it still happens on v20.5.

> What is Deepin's default firewall?

deepin-defender is not a community product, it should also already get removed from the community product.

> I believe that nothing should be imposed on the user, correct? Freedom is everything!

Since the most user of the deepin distro itself are Chinese people, and Duckduckgo is not available / not directly usable in China, we think listing that search engine is not a good idea.

> The reason for the update is because of the plethora of bugs and security fixes that were made by LibreOfffice developers that can be seen on various security sites

We do updates via our app store, and in the recent updates, we introduced a way to mark an app as outdated. If you find a package that's not up-to-date, you can use the app store to mark it so we can work on it.

Hope these answers can help. If you believe there is still issues we need to improve after trying deepin v20.5, please consider create new bug reports for individual bugs or create a discussion thread for suggestions.

Thanks again for your advice!
