### ISSUE TITLE
[Arch Linux] Can't take screenshot

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/developer-center#222]
It's impossible to take a screenshot on desktop if we right click before pushing the screenshot button.

**Comment by gustavodlima** [comment]
@funilrys Same here.

**Comment by wucke13** [comment]
Same here, also arch. My workaround was to press CTRL+Print for a delayed screenshot. However, screenshots should be available globally.

**Comment by hualet** [comment]
It's not possible to fix this at the moment as far as I know. Because menus grab keyborad and mouse, even if we can manage it to start deepin-screenshot at some point, keyboard events and mouse events still goes right to the menus other than deepin-screenshot, which replie on those events to interact with users.
@sonald
