### ISSUE TITLE
Bug theme dark.

### ISSUE THREAD

**Issue by GabrielMGitHub** [linuxdeepin/developer-center#2257]
1. Problem/Advice description
The dark theme is not being applied in deepin File Manager.

2. How to reproduce the problem
When activating dark theme.
3. Problem reproduce frequency
When activating dark theme.
Operating system :deepin
Desktop environment :dde

http://feedback.deepin.org/feedback/detail/2517

[deepin-log-1490730575183.tar.gz](https://github.com/linuxdeepin/deepin-gtk-theme/files/877400/deepin-log-1490730575183.tar.gz)
![deepinscreenshot20170328162852](https://cloud.githubusercontent.com/assets/8754997/24432853/375c559c-13fb-11e7-92fd-5c403188ba92.png)

**Comment by BLumia** [comment]
Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.

Native dark theme support has been introduced for all Deepin apps for a while. You can get the most recent version of deepin apps and have a try :)

Since it's resolved, I'll close this issue :)
