### ISSUE TITLE
Crashes when there are too many files

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#2266]
## Describe the bug
Deepin file manager crashes when it has to work on too many files at the same time.

## To Reproduce

To reproduce the bug, go to a directory where there are too many photos. Deepin file manager should crash at any moment then.

## Enviroments *(please complete the following information):*

 - Distro: Arch Linux
 - Version: 1.8.2

**Comment by BLumia** [comment]
Sorry for the late reply since I'm away from the file manager team for ~3 years now XD.

Now we're on deepin v20.5 with `dde-file-manager 5.5.10` released, this issue is hopefully resolved. If you like, please consider upgrading the package and see if this issue still happens. If it does still happen, please feel free to submit a new issue to report and I'll help you track this issue.

Thanks!
