### ISSUE TITLE
D-Bus security policy bug report.

### ISSUE THREAD

**Issue by openarun** [linuxdeepin/developer-center#2273]
Hi there,
Any updates on the following security issue?
https://bugzilla.opensuse.org/show_bug.cgi?id=1134132
Thanks!

-----

edited by maintainer:

- [ ] two "own=" lines one for root and one for everybody else. Especially bad since for example in the method `setUserSharePassword` cleartext passwords are passed.
- [x] daemon creates a log file in `/var/cache/deepin/dde-file-manager-daemon` (fixed: https://github.com/linuxdeepin/dde-file-manager/commit/c1c5628611f80de32cac931c8189dadbc48d5bee)
- [ ] the checkAuthorization() call (which is unused actually at the moment) uses the deprecated polkit UnixProcessSubject with PIDs.
- [x] setUserSharePassword: allows to set arbitrary users' smd password. (fixed: https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432)
- [x] addGroup: calls `groupadd` so regular users can create arbitrary groups. (fixed: https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432)
- [x] addUserToGroup: allows arbitrary users to add arbitrary other users to arbitrary other groups. (fixed: https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432)
- [x] restartSambaService calls `smbd restart` (fixed: https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432)
- [ ] TagManagerDaemon: disposeClientData: manages some tags for files that are stored in a per filesystem SQLite database.
- [x] UsbFormatter: mkfs: create jfs, ext2/3/4, btrfs, swap, hfs, dosfs, xfs, reiserfs on arbitrary paths. (interface already removed)
- [x] DeviceInfoManager: allow to call lsblk and various low level file system information tools on arbitrary block devices or other paths. (interface already removed)

**Comment by BLumia** [comment]
I’m back as a part of deepin team (what a coincidence!), and I've tracked this issue internally. 

As what already mentioned in https://github.com/linuxdeepin/developer-center/issues/2273#issuecomment-1072177065 most of them already resolved a long time ago, but there are still some related issues remaining. Anyway here is the current state of this issue:

----------

> - in the D-Bus configuration file com.deepin.filemanager.daemon.conf we find
>   the following:
> 
>   ```
>   
>   <policy user="root">
>     <allow own="com.deepin.filemanager.daemon"/>
>   </policy>
>   
>   
>   <policy context="default">
>     <allow own="com.deepin.filemanager.daemon"/>
>   ```
> 
>   There are two "own=" lines one for root and one for everybody else. This
>   allows any user to register this daemon (or actually: any program) on the
>   D-Bus system bus. It allows to hijack other users' D-Bus connections. This
>   is especially bad since for example in the method `setUserSharePassword`
>   cleartext passwords are passed.

This one still exists.

> - the daemon creates a log file in `/var/cache/deepin/dde-file-manager-daemon`.
>   First of all this is not the right place for a log file. Log files belong to
>   /var/log or /var/lib at best. Furthermore the log file is world readable
>   which should be avoided for logs originating from privileged programs.

Fixed in https://github.com/linuxdeepin/dde-file-manager/commit/c1c5628611f80de32cac931c8189dadbc48d5bee

> - the checkAuthorization() call (which is unused actually at the moment) uses
>   the deprecated polkit UnixProcessSubject with PIDs again. Like in the other
>   Deepin programs this needs to be changed to use the D-Bus SystemBusName
>   subject.

The interface still exists but seems it's unused. Might be okay to remove.

> Findings in the UserShareManager interface:
> 
> - setUserSharePassword: allows to set arbitrary users' smd password. Changes
>   the database in /var/lib/samba/private. If at all then this must only be
>   allowed for the caller's username.

Fixed in https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432

> - addGroup: calls `groupadd` so regular users can create arbitrary groups. Not
>   acceptable. Not acceptable interface without admin protection.

Fixed in https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432
  

> - addUserToGroup: allows arbitrary users to add arbitrary other users to
>   arbitrary other groups. Luckily doesn't work on SUSE, because
>   `/usr/sbin/adduser` is called but we have `useradd`. Not acceptable
>   interface without admin-protection.

The related interface no longer exists.

Fixed in https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432
  
> - restartSambaService calls `smbd restart`, shouldn't this go out to systemd
>   instead? Must also be authenticated.

The related interface no longer exists.

Fixed in https://github.com/linuxdeepin/dde-file-manager/commit/99a86b92590fd0ad52f2302ab66a7a3163168432

> Findings in the TagManagerDaemon:
> 
> - disposeClientData: manages some tags for files that are stored in a per
>   filesystem SQLite database. Doesn't look trustworthy. Why should everybody
>   be able to fiddle with tags?

This interface is still here but seems it's the intended behavior. I'll check again later.

> Findings in UsbFormatter:
> 
> - mkfs: create jfs, ext2/3/4, btrfs, swap, hfs, dosfs, xfs, reiserfs on
>   arbitrary paths. This can overwrite arbitrary regular files, too, if they
>   are large enough. Not acceptable interface without admin-authentication.

The related interface no longer exists.

> Findings in DeviceInfoManager:

The related interface no longer exists.

-----------

I also edited the description so we can check if they are all get fixed. Could you also check if I missed anything?

**Comment by SuperEffie** [comment]
Since you haven't answered for a long time, I will close this question first. If you have other questions or your questions have not been solved, welcome to create a new issue to follow it.
