### ISSUE TITLE
the case bookmarks do not support drag and drop appears again

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#2276]
The case bookmarks do not support drag and drop appears again. This time, it's not totally out of support.Dragging one to the top is OK, but it won't work to drag one to anywhere else, especially the bottom.

deepin 1002

**Comment by BLumia** [comment]
Hi, sorry for the late reply since we are not checking bug reports submitted outside the developer-center repo.

The issue should no longer exists in the most recent version of dde-file-manager (tested under `dde-file-manager 5.5.10-1` on deepin v20.5 and `deepin-file-manager 1:5.5.10-2` on Arch Linux), so I'll close this issue for now.

If you still have this issue on the most recent version you can get, please consider submitting a new issue and we'll track the issue there. Thanks!
