### ISSUE TITLE
DDE Filemanager is showing huge number of small diskpartition

### ISSUE THREAD

**Issue by aadarshadhakalg** [linuxdeepin/developer-center#2284]
My system has large number of small disk partition. How to get rid of those all? 
![Screen Capture_dde-file-manager_20201110235435](https://user-images.githubusercontent.com/19362725/98714913-90c5d580-23b1-11eb-8cb6-eb3da3e9e0c2.png)

**Comment by BLumia** [comment]
Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.

According to @itsXuSt. Deepin File Manager introduced an option to control whether to show those loop partitions, please update to the latest `dde-file-manager` release and see if it resolved your issue, and feel free to open another issue if you still got similar issues. Thanks!
