### ISSUE TITLE
[deepin 20] [Bug] File integrity was damaged on gvfs media

### ISSUE THREAD

**Issue by abimagnus** [linuxdeepin/developer-center#2300]
I am getting this error when copying files to my Android phone through USB cable in the V20 file manager. "File integrity was damaged"
It works fine when I use Nautilus !

![Screen Capture_20201011184946](https://user-images.githubusercontent.com/8939183/95679761-9d101480-0bf2-11eb-96c2-fbc32c85b7ea.png)

**Comment by BLumia** [comment]
Sorry for the super late response since we were not looking into issues that were reported outside the developer-center repo.

I cannot reproduce this issue on deepin v20.4 with dde-file-manager 5.5.3-1. Since the original bug reporter no longer uses deepin and we cannot verify if it still exists on some special condition, if you have a similar issue, please consider creating a new issue and provide necessary detailed information so we could look into it. Thanks!
