### ISSUE TITLE
Dark Menu in FireFox used on Deepin

### ISSUE THREAD

**Issue by njmulsqb** [linuxdeepin/developer-center#2351]
Hi,

I have just recently installed Deepin Desktop Environment over my Ubuntu 20, I have previously used GNOME, KDE, MATE etc and have not faced this problem there.

The issue, is when I right click in Mozilla Firefox, the menu is in dark color and the text is unreadable, its readable only if I hover on some item. It seems a UI issue with Deeping DE

Here's a screenshot for reference.

**Comment by babyfengfjx** [comment]
Thank you for your feedback.Due to no reply for a long time and lack of necessary information, no such phenomenon has been found in the latest version,closing this issue for now. If the problem still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue.
