### ISSUE TITLE
File Manager instantly closes connection when trying to connect to SFTP

### ISSUE THREAD

**Issue by GNUxeava** [linuxdeepin/developer-center#2356]
# Steps to reproduce
Click on the menu to the left of minimize button > Connect to Server > enter your sftp address > enter username and password 

It will try to connect and then close with the message "Unable to access sftp:[address],port=[port]"

# Version
5.5.3

# OS Version
Version: 20
Edition: Community (20.3)
Kernel: 5.10.60-amd64-desktop

# Screenshot
![image](https://user-images.githubusercontent.com/21287366/153906190-3810757e-499d-4eec-b795-f3a348ac2698.png)

**Comment by babyfengfjx** [comment]
I wonder if this problem still exists in the latest version?
We are sorry that we are unable to reproduce this issue at this time, but perhaps we can communicate further in order to move forward with identifying this issue.
![image](https://user-images.githubusercontent.com/24642999/160332453-510c79b8-7d6e-4f97-a211-ea14062ca9ab.png)

**Comment by GNUxeava** [comment]
Tried reproducing the issue. Seems to work fine now. I think we should close this issue.
