### ISSUE TITLE
Please do not close issues without comment

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/developer-center#2389]
https://github.com/linuxdeepin/deepin-desktop-schemas/issues/2
was closed without comment reagrding the issue or its solution.
Has it been looked at?
Has it been worked on?
Has it been discussed internally?
Has it been fixed?
Has it been declined?

It takes time and effort to create and submit tickets, so please at least include some information what happened to it when closing tickets. Thank you very much.

**Comment by BLumia** [comment]
Hi, sorry for the late response.

We are sorry we did that before, and we had missed a lot of feedback from the community. To address this problem, we now have a guideline about how to correctly response to community feedback, so _hopefully_ this won't happen again.

Since there are a lot of issues we might miss, we are also going to go through the ancient issue reports and see what we can do about them. You can also see #2831 about the detail plan.

I'll close this issue for now. If you still have any questions to ask or have suggestions / feedback, please feel free to open a new discussion thread.

Thanks!
