### ISSUE TITLE
three vulnerable bugs in deepin-image-viewer 

### ISSUE THREAD

**Issue by Kaka201** [linuxdeepin/developer-center#2416]
1，Invalid address access
![image](https://user-images.githubusercontent.com/38719975/92209962-80c8db80-eec0-11ea-8a6d-c069fdcabfb3.png)
2，Null pointer dereference
![image](https://user-images.githubusercontent.com/38719975/92210160-c9809480-eec0-11ea-8eb8-eba0c7490693.png)
3，div by zero
![image](https://user-images.githubusercontent.com/38719975/92210341-1f553c80-eec1-11ea-8650-2dcb46e60e13.png)

**Comment by BLumia** [comment]
Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.

We have a dedicated security team to process vulnerable bugs now, and since It's have been for a while, the issues you've mentioned might already been addressed. So I'll close this issue for now.

If you believe the issues you reported still exist, please consider creating another issue with the necessary detailed information so we can reproduce and look into it. Thanks!
