### ISSUE TITLE
deepin-movie: List all supported mime types in desktop file?

### ISSUE THREAD

**Issue by petterreinholdtsen** [linuxdeepin/developer-center#2430]
Hi. I notice from https://wiki.debian.org/DebianMultimedia/PlayerSupport, the deepin video player list a lot less supported video formats in its desktop file. Could it be that some supported formats are missing from the desktop file?

**Comment by BLumia** [comment]
Closed since resolved :)

**Comment by petterreinholdtsen** [comment]
[Gary Wang]
> Closed since resolved :)

Sound good.  Where can I find the latest list of supported MIME types
that will show up in the deeping-movie .desktop file?

I tried searching in the repo for video/mpeg, which is a format
supported by most video planers, without finding it anywhere in the
code.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by BLumia** [comment]
> Where can I find the latest list of supported MIME types
> that will show up in the deeping-movie .desktop file?

Since it's mpv based, check out [what mpv supported](https://github.com/mpv-player/mpv/blob/master/etc/mpv.desktop) and strip out all non-video mime types could be fine :)

> I tried searching in the repo

This is the developer-center repo for all DDE/deepin related issues and general feedback. You may want to check out https://github.com/linuxdeepin/deepin-movie-reborn

If you still have other questions to ask, feel free to [open a discussion thread](https://github.com/linuxdeepin/developer-center/discussions) and let's discuss there :)
