### ISSUE TITLE
Window controls appearing not reliable

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#2432]
Usualy on mouse move or mouse enter the window controls would appear. That seems to happen on random.

**Comment by BLumia** [comment]
Hi, sorry for the late reply since we are not checking bug reports submitted outside the developer-center repo.

This issue should no longer exist in the most recent version of deepin-movie-reborn (tested under deepin v20.5 with `deepin-movie 5.9.14-1`), so I'll close this issue for now.

If you still have this issue on the most recent version you can get, please consider submitting a new issue with detailed information so we can look into it. Thanks!
