### ISSUE TITLE
deepin 20 stuck at the deepin loading screen

### ISSUE THREAD

**Issue by Quartz15** [linuxdeepin/developer-center#2436]
hi, I've had deepin 20 for a little while now and then out of the blue it gets stuck on the deepin loading screen and doesn't change. im not really sure what i should do.

**Comment by BLumia** [comment]
Sorry for the super late reply since we didn't look into issues that were created outside the developer-center repo.

Do you still have this issue on the most recent version of deepin (we are on v20.5 now)? If you do, please consider opening a new issue and provide the necessary detailed information (fill in the issue template will be a good start) so we can look into it. Thanks!
