### ISSUE TITLE
deepin-picker: Having trouble with multi monitor environment

### ISSUE THREAD

**Issue by PicoSushi** [linuxdeepin/developer-center#2448]
I'm trying to use deepin-pciker, but it doesn't fit to real screen. I have three monitors, so this might not compatible with this environment.

**Comment by SuperEffie** [comment]
Sorry for no reply for a long time and thank you for your feedback. Our system has been updated to deepin v20.5. deepin-picker-cli has been updated to 5.0.24. It works fine with two monitors connected, using either duplicate mode or extend mode. Your issue seems to have been fixed. If your problem still exists, please contact us and  our developers will help you deal with it
