### ISSUE TITLE
Power plugin is broken ..again

### ISSUE THREAD

**Issue by carloalbertobarbano** [linuxdeepin/developer-center#2469]
The battery icon does not update when the laptop is charging, and it shows "0 min remaining"

**Comment by BLumia** [comment]
Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.

According to @0yanghongwei this issue is resolved a long time ago so I'll close it for now. Feel free to create another issue if you have got a similar issue.

@qiuzhiqian Hi and please consider [creating another discussion thread](https://github.com/linuxdeepin/developer-center/discussions) about different feature request so we could track feature requests more effectively. Thanks!

**Comment by carloalbertobarbano** [comment]
It's okay, I moved to arch btw
