### ISSUE TITLE
Crashes after overnight update

### ISSUE THREAD

**Issue by The1Magoo** [linuxdeepin/developer-center#2470]
Hi.. Running UbuntuDDE.  some updates came through last night, and after starting this morning the dock has been unstable - opening most applications causes the dock to disappear.

running pkill dde-dock; dde-dock restores it until another application is started.

The only errors I can see are :

QObject::connect(IndicatorTrayWidget, IndicatorTray): invalid null parameter

and

"dtkwidget" can not find qm files

and

"dde-disk-mount-plugin" can not find qm files

Unsure what other info to provide, but obviously willing to assist if I can..

Thanks, Dave

**Comment by tsic404** [comment]
this should be fixed, still have question ?

**Comment by BLumia** [comment]
Closing since seems resolved. If you still have a similar issue, please consider creating a new issue so we can look into it.

By the way, if it's a UbuntuDDE-only issue, it's strongly suggested to report to their bug tracker and then report to us when it's confirmed as an upstream issue :)

Thanks!
