### ISSUE TITLE
Microsoft Teams shows double icon in task-bar quick settings panel

### ISSUE THREAD

**Issue by tanvir-10** [linuxdeepin/developer-center#2479]
![image](https://user-images.githubusercontent.com/47321309/93740547-8b97a600-fc0c-11ea-943b-8cb90548d0e5.png)

**Comment by babyfengfjx** [comment]
Thanks  for your feedback,Currently on the latest version of the issue  should have been solved, if using the latest version of the system still have problems, but also prompt feedback，Due to no reply for a long time , closing this issue for now. If the issue still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue.
