### ISSUE TITLE
[Question] How to restore the default "Push Notification" deepin os?

### ISSUE THREAD

**Issue by aprilahijriyan** [linuxdeepin/developer-center#2530]
![image](https://user-images.githubusercontent.com/37798612/106809698-9116f980-669e-11eb-9123-5bdc2ce66168.png)
Hi, I don't really understand why my "Push Notification" has changed, is there any way to restore it to the original? 

Thank you in advance.

**Comment by BLumia** [comment]
Hi, sorry for the super late response since we're not checking issues outside the developer-center repo.

The notification on your screenshot seems to be not the one provided by deepin. If you installed components from other DEs then maybe it took the deepin's d-bus interface which may cause this issue.

I cannot reproduce this issue now on my deepin installation (deepin v20.4) and since it's already been a year, if it's a bug then it's probably already fixed, so I'll close this issue for now. If you still have this issue on your installation, please feel free to create a new issue about this and provide some details, so we could look into it.

Thanks!
