### ISSUE TITLE
Add two fingers swipe back and forward gesture

### ISSUE THREAD

**Issue by sayantan-das-bchu** [linuxdeepin/developer-center#2548]
Recently I've started using this distribution. And like it a lot. Can you guys please help me to two fingers swipe back and forward gesture?

I've added the following to ```/usr/share/dde-daemon/gesture.json``` with no luck.

```
{
        "Name": "swipe",
        "Direction": "right",
        "Fingers": 2,
        "Action": {
            "Type": "commandline",
            "Action": "xdotool key alt+Left"
        }
    },
    {
        "Name": "swipe",
        "Direction": "left",
        "Fingers": 2,
        "Action": {
            "Type": "commandline",
            "Action": "xdotool key alt+Right"
        }
    }
```

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that were reported outside the developer-center repo.

Since it's for a while and we are on deepin v20.5 now, I'll close the issue for now. You can update the package and see if it still doesn't work. If it's still not working, please create a new issue ticket to report the bug. Thanks!
