### ISSUE TITLE
Non-english keyboard layout - programs shortcuts doesn't work (CTRL+C etc...)

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#2559]
## Describe the bug
When selected keyboard layout is russian (i suspect any language which is not english) - any program shortcuts doesn't work (CTRL+C / CTRL+V / CTRL+S etc)

## To Reproduce
Any program to my knowledge, for example Sulbime text 3

## Expected behavior
All shortcuts of a program should work regardless of keyboard layout language selected.

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.8-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
Arch / Manjaro Deepin

### Related package version
No idea

### Additional context
This started somewhere in course of 2 months from now, in cycle of moving to deepin-kwin etc.

@BLumia 
Please take a look at this, seems to me like pretty serious bug for anyone - because it limits workflow of people who use more than one keyboard layouts.

**Comment by tsic404** [comment]
I test this on deepin (20.5), switch language and keyboard to russian, shortcut works, do you sill get this problem?

**Comment by BLumia** [comment]
Closing since resolved. If you are still facing similar issues, please create a new issue to report.

There might still be some issues with keyboard layout and IME support on DDE when using non-English language/keyboard layout. We cannot easily test if our fix works as intended in all keyboard layouts/IMEs, so if you still facing problem using an IME or switching keyboard layout under DDE and/or deepin, please create a new issue and let us know so we could work it out together. (At the time of writing) We also have other related enhancements so you can contact us by opening a new issue and we may provide some pre-release version so you can test it out if you like.
