### ISSUE TITLE
[Open] Larger than standard launcher icons in Arch Linux Rolling V20.1 

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2596]
https://github.com/felixonmars/dde-launcher/issues/1

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/168511436-eb5a12be-75c1-470a-935b-c9d747f78059.png)

Sorry for the super late reply.

This issue seems to no longer exist on the most recent version of DDE on Arch Linux. So, I'll close it for now.

If you are still facing this issue, please open a new issue with detailed information so we can look into it. Thanks!
