### ISSUE TITLE
[Gentoo]Window effect can not turn on

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/developer-center#2610]
Window Effect is automaticly turned off just after turned on. How to fix this issue?

KWin version: 5.18.4.1
Patch for building: [dde-kwin-5.0.14.1-kwin-5.18-override-error.patch](https://github.com/zhtengw/deepin-overlay/blob/master/x11-wm/dde-kwin/files/dde-kwin-5.0.14.1-kwin-5.18-override-error.patch)

![Gentoo - VMware Workstation 2020-05-06 13-27-54 mp4_20200506_140349](https://user-images.githubusercontent.com/3148769/81142532-7d6d2400-8fa2-11ea-87a8-556a417b1557.gif)

**Comment by BLumia** [comment]
Sorry for the super late reply since we didn't look into issues that were created outside the developer-center repo.

You may need to do what https://github.com/linuxdeepin/developer-center/issues/2610#issuecomment-626050864 says, and if that still doesn't work, you may also want to try if deepin-wm works. Anyway, since you are using KWin and according to the description you provided, it's very unlikely to be a DDE related bug. (btw, if you can install KDE, you can also check if window effect can be enabled in KDE's `systemsettings`. If not, then it's definitely not related to DDE.)

I'll close this one for now since even if it's a bug it might be resolved in the ~2 years updates. If you still have this issue on the most recent version, please create a new issue with detailed information so we can look into it. Thanks!
