### ISSUE TITLE
[Security bug] Logged-in account lock bypass<周二>

### ISSUE THREAD

**Issue by okaminoseishin** [linuxdeepin/developer-center#2656]
# It's possible to unlock already logged-in account without touching keyboard at all

Bug does not appear at every attempt, but often, if one of following conditions takes place:
* If you set custom background, sometimes you can see default background while lock screen loads. If it's your case - bug will appear, even after suspend(I can't check if hibernation is a case)
* If `dde-lock` wasn't reloaded after segfault(just my assumption), i.e. not enough time passed between login/unlocking and locking again, ~ 10+ minutes in my case
* At locking right after unlocking appears every time

May be related to linuxdeepin/developer-center#286 

## To Reproduce

1. Log in to account
2. Lock it
3. Click on "Switch user" icon
4. User portrait will not show, deepin logo appears instead and will be freezed to the left side of the screen
5. Just click on it and you are in

## Expected behavior

*The same as if you are not logged in*

### Distro & Version

Arch linux, last full update at 11.12.2018
Linux hostname 4.19.7.a-1-hardened linuxdeepin/developer-center#1 SMP PREEMPT Thu Dec 6 03:19:15 CET 2018 x86_64 GNU/Linux

### Related package version

dde-lock 2015.1.0 (deepin-session-ui 4.7.0-1)

## Additional information

1. I have one user in system, main group same as username plus groups wheel, lp, input
2. I have fprintd installed, but **not** configured(PAM settings untouched), one fingerprint enrolled
3. `dmesg` shows segfault:
`[ 2316.463888] dde-lock[5627]: segfault at 14 ip 00000c970b46ce12 sp 00007a66c0d34850 error 4 in dde-lock[c970b457000+77000]`
`[ 2316.463902] Code: 5d 41 5c 41 5d 41 5e 41 5f c3 66 0f 1f 44 00 00 48 8d 6c 24 50 48 8d 5c 24 70 48 89 ef ff 15 75 f1 1b 00 49 8b 45 00 48 89 df <8b> 70 14 ff 15 15 e1 1b 00 be 03 00 00 00 48 8d 3d 54 9b 19 00 ff`
`[ 2316.463942] audit: type=1701 audit(1544568503.422:140): auid=1000 uid=1000 gid=1000 ses=3 pid=5627 comm="dde-lock" exe="/usr/bin/dde-lock" sig=11 res=1`

**Comment by BLumia** [comment]
Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.

I did test this issue under deepin v20.4 with the reproduce steps you provided and I cannot reproduce this issue. There are also no `dde-lock` related errors in `dmesg` output. It's been a long time so I guess the issue has been addressed already if it exists.

Since it cannot be reproduced, I'll close this issue for now. If you have similar issues or believe you can still reproduce this issue under deepin v20.4 or above, please consider creating another issue with the necessary detailed information so we can look into it. Thanks!
