### ISSUE TITLE
the icon of button disappear.

### ISSUE THREAD

**Issue by alieonsido** [linuxdeepin/developer-center#2666]
Hi.
As title: 
![image](https://user-images.githubusercontent.com/14144668/82006243-f272e480-9699-11ea-91b8-298257402499.png)

you can see that: left hand side icon of option button is disappeared.

Environment: Linux arch 5.6.11-arch1-1 linuxdeepin/deepin-screen-recorder#1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux
Application Version: up-to-date by Pacman.

How do I deal with these?
Thanks for your reply.

**Comment by BLumia** [comment]
![image](https://user-images.githubusercontent.com/10095765/165237350-860d0c24-b897-43a1-9124-41f946bf7d8d.png)

I believe this already got fixed in the most recent release. (The above screenshot takes on Arch Linux)

If you still have this issue, please let us know by creating a new bug report so we can look into it. Thanks!

**Comment by Hacksign** [comment]
> 

Not exactly.

There was icons when I have a fresh installed OS, but these icons lost again when I change my default icon by:

```
ln -svf /usr/share/icons/<my-icon-theme> /usr/share/default
```

Maybe there are some missing icons, but I can not figure out which one ;(
