### ISSUE TITLE
Not working ( defaced ) under Manjaro KDE

### ISSUE THREAD

**Issue by EugenMayer** [linuxdeepin/developer-center#2670]
While deepin-screenshot is and was working just fine, deeping-screen-recorder is entirely defaced on latest Manjaro KDE.

Using Manjaro 20.0.3 with the latest patches applied.

In particular what is broken is:

 - no labels are shown on the buttons at all ( missing translations or keys? )
 - the UI looks scaled, broken / ugly ( well i'am not sure how it should look like, i just hope it is not that
 
In addition and even more troubling is, taking a screenshot takes about 1 minute freezing the entire PC in the meantime.

Downgrading and installing deepin-screenshot fixes that.

**Comment by BLumia** [comment]
Sorry for the super late response since we were not looking into issues that were reported outside the developer-center repo.

I've tested under `Manjaro KDE 21.2.5` with `deepin-screen-recorder 5.10.9-3` and it should be working under an x11 session.

Since I cannot reproduce this issue and we are processing a huge number of issues that were transferred from other repos. If you still have this issue, please consider creating a new issue with the necessary detailed information provided, so we can look into it. Thanks.

Also see: #2680

**Comment by EugenMayer** [comment]
Moved on a long time ago, using flameshot - thus cannot helpf reproducing- beside this is the obvious, always present issue with QT apps :)
