### ISSUE TITLE
Uninstall on ubuntu

### ISSUE THREAD

**Issue by guptadhaval18** [linuxdeepin/developer-center#2679]
I installed from ubuntu software. After which when I am trying to remove the application, it says "the following pack have unmet dependencies".

**Comment by BLumia** [comment]
Hi, sorry for the super later response since we were not checking issue reports that were created outside the developer-center repo.

"The following packages have unmet dependencies" is usually caused by other broken packages that should be listed followed that sentence. You need to fix the package dependencies issue before continuing using `apt` to install/uninstall packages.

Since it's not caused by deepin-screen-recorder then I'll close this issue for now. If you believe it's caused by deepin-screen-recorder and if you can still reproduce the issue you got, please feel free to create another issue with the full error message you've got so we could look into it. Thanks!
