### ISSUE TITLE
current nVidia GPU

### ISSUE THREAD

**Issue by LordIGR** [linuxdeepin/developer-center#2694]
In current video cards such as nvidia, there is no option to use different nouveau drivers, this leaves many users out of the deepin, because they can not enable the HDMI output for a second monitor.

**Comment by BLumia** [comment]
Sorry for the super late reply since we didn't look into issues that were created outside the developer-center repo.

deepin-graphics-driver-manager project is no longer under active maintained, so I'll close this issue for now. Similar projects might be started in the future so stay tuned :)

link: #2704 #3000
