### ISSUE TITLE
Can not switch in arch linux

### ISSUE THREAD

**Issue by OswinWu** [linuxdeepin/developer-center#2695]
I've built this application in arch linux, it can run but can't switch driver.

**Comment by BLumia** [comment]
Sorry for the super late response since we did not look into issues that were created outside the developer-center repo.

`deepin-graphics-driver-manager` is actually tightly coupling to the deepin distro, it will reboot the OS to overlayfs and try to install the driver, and do the actual install after the check succussed. So, I'm afraid it won't work in Arch Linux.

btw, since you are using Arch, it's strongly recommended to do the graphic driver installation thing _manually_ so you'll know the exact detail if anything went wrong, as that's what Arch Linux designed to be used.

If you have any other questions, feel free to [create a discussion thread in the discussion board](https://github.com/linuxdeepin/developer-center/discussions).
