### ISSUE TITLE
Graphics Driver Manager does not supported Radeon HD 6470M and Intel HD 3000 

### ISSUE THREAD

**Issue by nalawneh-co** [linuxdeepin/developer-center#2704]
Hi all,

My laptop with hybrid **Intel HD 3000/Radeon HD 6470M** graphics cards and the graphics manager do not support them, please see below screenshot:

![DeepinScreenshot_select-area_20190614114432](https://user-images.githubusercontent.com/24733255/59496334-dc611080-8e99-11e9-82bc-8ac44f4e7ced.png)

also, I cannot adjust the brightness of the display correctly and this causes eye strain.

deepin version: 15.10.1

Thanks

**Comment by BLumia** [comment]
Sorry for the super late reply since we didn't look into issues that were created outside the developer-center repo.

deepin-graphics-driver-manager project is no longer under active maintained, so I'll close this issue for now. Similar project might be started in the future so stay tuned :)

link: #3000
