### ISSUE TITLE
Active theme not checked

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#2711]
I just changed my theme from Numix to deepin-dark. It really did change in the system, but not in the settings.

![image](https://user-images.githubusercontent.com/6298761/65756747-fb687300-e115-11e9-9e0e-f713f1d663a0.png)

**Comment by BLumia** [comment]
Sorry for the super late response since we were not checking issue reports created outside the developer-center repo.

Now we are on deepin v20 and the system settings part changes a lot, so I'll close this issue for now. Please feel free to create another issue if you have problem using the most recent version of deepin or DDE.
