### ISSUE TITLE
boot error message shown during boot on deepin 15.4 official release

### ISSUE THREAD

**Issue by cyc0ol** [linuxdeepin/developer-center#275]
Just installed fresh copy of the deepin latest version but on boot whether booted on usb or have installed on my ssd it shows error "**ata1:00: failed to set xfermode (err_mask=0x40)**"

does anyone had this error?  thanks

**Comment by yyyeerbo** [comment]
ATA bus error

ATA bus error means that data corruption occurred during transmission over ATA bus (SATA or PATA). This type of errors can be indicated by

    ICRC or ABRT error as described in the section called “ATA/ATAPI device error (non-NCQ / non-CHECK CONDITION)”.

    Controller-specific error completion with error information indicating transmission error.

    On some controllers, command timeout. In this case, there may be a mechanism to determine that the timeout is due to transmission error.

    Unknown/random errors, timeouts and all sorts of weirdities. 

As described above, transmission errors can cause wide variety of symptoms ranging from device ICRC error to random device lockup, and, for many cases, there is no way to tell if an error condition is due to transmission error or not; therefore, it's necessary to employ some kind of heuristic when dealing with errors and timeouts. For example, encountering repetitive ABRT errors for known supported command is likely to indicate ATA bus error.

Once it's determined that ATA bus errors have possibly occurred, lowering ATA bus transmission speed is one of actions which may alleviate the problem. See the section called “Reconfigure transport” for more information. 


Reconfigure transport

For both PATA and SATA, a lot of corners are cut for cheap connectors, cables or controllers and it's quite common to see high transmission error rate. This can be mitigated by lowering transmission speed.

The following is a possible scheme Jeff Garzik suggested.

    If more than $N (3?) transmission errors happen in 15 minutes,

        if SATA, decrease SATA PHY speed. if speed cannot be decreased,

        decrease UDMA xfer speed. if at UDMA0, switch to PIO4,

        decrease PIO xfer speed. if at PIO3, complain, but continue 

Hope that explain why the error happens.  Usually, it has no harm

**Comment by cyc0ol** [comment]
Currently i am using SDD with my laptop just wondered why it has error message while booting, if it has no hard at all then i shall close this issue
