### ISSUE TITLE
utf-8 devnagari font not rendered correctly

### ISSUE THREAD

**Issue by aksharlabs** [linuxdeepin/developer-center#2786]
thish is correct rendered text 

![Screen Capture_select-area_20210102222558](https://user-images.githubusercontent.com/74598801/103458263-ab7d5080-4d49-11eb-9e31-4c93eac3e168.png)
 this is same text on terminal

![Screen Capture_deepin-terminal_20210102222544](https://user-images.githubusercontent.com/74598801/103458266-b33cf500-4d49-11eb-9e5e-6892556af174.png)

**Comment by babyfengfjx** [comment]
Due to the prolonged lack of follow-up on this issue, deepin has now entered the V23 version with many updates and iterations. We are unsure if this problem has been resolved in the new version. Therefore, we will close this issue for now. If you encounter any further problems, please provide detailed environmental information, and we will follow up accordingly. Thank you very much for your feedback.

**Comment by nepvibes** [comment]
Still, after all these years, Deepin Terminal fails to render Devanagari fonts correctly. This bug severely limits usability for users working with South Asian scripts. In contrast, both GNOME Terminal and Konsole handle Devanagari rendering flawlessly. It’s long overdue for Deepin Terminal to support proper font shaping and Unicode compliance for Indic scripts.

**Comment by BLumia** [comment]
Let's move to https://github.com/orgs/linuxdeepin/discussions/11971 for follow up discussion
