### ISSUE TITLE
Slowly to switch between applications

### ISSUE THREAD

**Issue by rafaeldev** [linuxdeepin/developer-center#2818]
![image](https://user-images.githubusercontent.com/4596160/93097101-83bf8b00-f67b-11ea-93cf-9331ca54c22a.png)

Pressing `alt` and typing `tab` many times doesn't effect to pages alternate times.
I think so which animation are "blocking" the bind altenate.

That behaviour for reverse alternate is equal with a detail: When press first time (`alt +shift + tab`) de event are not fired.

![Screen Capture_google-chrome_20200914111856](https://user-images.githubusercontent.com/4596160/93097684-43acd800-f67c-11ea-972d-4568ca052698.gif)

**Comment by SuperEffie** [comment]
Sorry for no reply for a long time and thank you for your feedback. Our system has been updated to deepin v20.5.  It works fine whlie I am pressing alt and typing tab many times. Your issue seems to have been fixed.Now I close this issue. If your problem still exists,you can apply to reopen it,and please contact us and our developers will help you deal with it.
