### ISSUE TITLE
Icons in tabbox moving / shuffling / changing order

### ISSUE THREAD

**Issue by RedBearAK** [linuxdeepin/developer-center#2821]
I just installed Deepin 20.2 in a GNOME Boxes virtual machine and when I try to Alt+Tab between applications the icons in the switcher (tabbox) are moving around while the switcher dialog is displayed on screen. 

I've never seen any other Alt+Tab switcher on any operating system, distro or desktop environment behave this way. I'm using KDE Neon as my main desktop, so it's using the same kwin/tabbox switcher. I've never seen its icons re-order or shuffle themselves while I'm trying to switch applications. 

This effect might not be seen easily when Deepin is installed on bare hardware with graphics acceleration working. But inside a virtual machine where the effects are quite slow, it is very obvious that the icons are shuffling themselves around while I'm Alt+Tabbing to different windows. It makes the Deepin Alt+Tab switcher almost useless, often switching me to a completely random application.

**Comment by BLumia** [comment]
Hi, sorry for the super late reply since we didn't really notice issues that were created outside developer-center before (see the pinned issue for detail).

I have tested this issue with a VirtualBox VM with 2GB memory allocated and 64GB disk space, with Deepin v20.4 installed and dde-kwin 5.4.19-1. The issue you mentioned seems to no longer exist.

Please consider try update Deepin and see if it still exists. If you still got similar issues, please feel free to create a new issue and provide the necessary details so we could look into it.

Thanks!
