### ISSUE TITLE
Shortcuts are not working on arch linux

### ISSUE THREAD

**Issue by franciscocpg** [linuxdeepin/developer-center#2823]
Some shortcuts like Alt+TAB currently are not working using deepin-kwin on arch linux.

**Comment by BLumia** [comment]
Sorry for the super late response since we were not checking issue reports created outside the developer-center repo.

Though deepin-kwin is somehow broken under Arch Linux, but the <kbd>Alt + Tab</kbd> is actually working in `deepin-kwin 5.3.14-1` 😂 

I'll close this one for now. Please feel free to create a new issue if you still have issues when using the most recent version.
