### ISSUE TITLE
deepin-browser: Where is the source code?

### ISSUE THREAD

**Issue by mlavik1** [linuxdeepin/developer-center#3064]
It seems like the repository has no branches with any code in it. Is that a mistake, or has the code been moved to somewhere else?

**Comment by BLumia** [comment]
Hi, sorry for the late reply since we were not checking issue reports that were created outside the developer-center repo.

The deepin-browser(uosbrowser) is based on the Chromium project, but it's (currently) not open-sourced. I'm not sure if the related team have plans to open-source it, please stay turned for future updates :)
