### ISSUE TITLE
Please Update your browser Banner Pop-up

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#3065]
![Screenshot_org deepin browser_20210515202546](https://user-images.githubusercontent.com/45546591/118365293-c4c9bf80-b5bb-11eb-8fa2-0ec999d7c768.png)

**Comment by BLumia** [comment]
The most recent version of the browser (`5.5.3`) is based on chromium `93.0.4577.63` now so I guess this issue should no longer exist. Also, the text displayed on that page is returned from WhatsApp's server so we probably couldn't alter the content. Since deepin-browser is chromium-based, so I guess it's okay...sort of ;p

Please feel free to create a new issue if you have a similar issue.

Thanks!

**Comment by sarojpoudel33** [comment]
https://user-images.githubusercontent.com/45546591/167791822-d44e3541-0e4f-4efb-afd0-081c1a79d023.mp4

**Comment by BLumia** [comment]
That's weird. My network cannot access WhatsApp so I'm not be able to test it, could you check if set another User Agent (in F12 > the gear icon) will work? Also, could you provide the information shows at `chrome://version/`? Thanks!

![image](https://user-images.githubusercontent.com/10095765/167793953-4cf49f99-f612-4887-80c6-3a99fa05f288.png)

**Comment by BLumia** [comment]
I tested under another network. Can confirmed it's a user-agent issue.

For the most recent release of deepin browser (`org.deepin.browser 5.5.3-1`) the default user agent is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36 UOS`. The issue will appear when accessing https://web.whatsapp.com while using that user agent string. Modify the UA string that remove the UOS part can solve this issue: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36`.

As a workaround, you can modify the User Agent string as said above. Also, third-party chromium extension that can be used to help you switch User Agent can also be used (can be installed from `chrome://extensions`).

Since this is WhatsApp's problem so there is probably nothing we can do :/

Hope that helps.
