### ISSUE TITLE
Current lyrics line should be bigger, and the transition should be animated

### ISSUE THREAD

**Issue by Wazzaps** [linuxdeepin/developer-center#3075]
The color contrast isn't enough, I would recommend enlarging the text by 125-150%.
I tried implementing this myself, here's a broken patch (for `src/music-player/view/widget/delegate/lyriclinedelegate.cpp`):

Before:
```cpp
    painter->drawText(option.rect,
                      Qt::AlignCenter | Qt::TextWordWrap,
                      index.data().toString());
```

After:
```cpp
    // Make the current lyric line bigger
    if (option.state & QStyle::State_Selected) {
        QRect newRect = option.rect.translated(0, 0);
        newRect.setLeft(-(newRect.width() / 3));
        newRect.setTop((newRect.height() * 2));
        painter->scale(1.5, 1.5);
        painter->drawText(newRect,
                          Qt::AlignCenter | Qt::TextWordWrap,
                          index.data().toString());
    } else {
        painter->drawText(option.rect,
                          Qt::AlignCenter | Qt::TextWordWrap,
                          index.data().toString());
    }
```
It works for a while but then breaks and occasionally segfaults. (wtf?)
I got these numbers by playing with it, I have no idea why they work.
In any case I'm a Qt noob so someone with better expertise will implement this better.

Also, it would be nice if the lyrics animated instead of jumping, kinda like [Apple Music (video link)](https://twitter.com/i/status/1230282846071291905).
It could be implemented like this ([idea taken from here](https://forum.qt.io/topic/5816/solved-qlistview-scrolling-animation)):
- Get the position of the item to scroll to in your view (using QListView::visualRect())
- Get a handle on the vertical scroll bar of the list view
- Create a QPropertyAnimation to animate the value property of the vertical scroll bar to a value that will get your item into view

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that reported outside the developer-center repo.

Personally, I think increasing text size couldn't resolve a color contrast issue. Now we're on deepin v20.5 with a brand new deepin-music release, you may like check if the most recent version of deepin-music still have the issue you mentioned. If it still has issues, please feel free to create a new issue to report, and since we now again accept Pull Requests, you can also create PR if you like and we'll see if we can get it merged :)
