### ISSUE TITLE
deepin-music not respond and freeze

### ISSUE THREAD

**Issue by graymind75** [linuxdeepin/developer-center#3081]
Hi
I'm using deepin-music for a while, after last update player not respond and freeze until force it to close like the image below
delete and reinstall not help at all
this is the log from cli: https://pastebin.com/QeZu6wTr

OS: ArchLinux
Kernel: x86_64 Linux 5.4.49-1-lts
DE: Gnome
WM: Mutter
CPU: Intel Core i7-4790K @ 8x 4.6GHz
RAM: 16GB

![image](https://user-images.githubusercontent.com/22690689/86536851-1e734f00-bf00-11ea-8dbb-bb422882f70a.png)

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that were created outside the developer-center repo.

The issue were created in 2020 and deepin-music changed a lot in the 2 years. If that still happens in the most recent version you can get, please open a new issue in developer-center repo and we'll look into it. Thanks!
