### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by m1cl** [linuxdeepin/developer-center#3082]
I cannot play any music.
this is what I found: 
daemon/audio[6915]: audio_config.go:217: open /var/lib/deepin-sound-player/config-1000.json: permission denied

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that were created outside the developer-center repo.

deepin-music (the repo where you created this issue) is not related to deepin-sound-player, and we might need more detail to know what's exactly going on.

As deepin already update to v20.5, the no audio issue might already be resolved so I suggest try upgrade your system and see if that resolved this issue, if that doesn't resolve the issue, please create a new issue in the developer-center repo using the issue template, and we'll look into it. Thanks!
