### ISSUE TITLE
Music crash on open file dialog

### ISSUE THREAD

**Issue by laradvance** [linuxdeepin/developer-center#3083]
when opening Add music or open folder, it freeze

![Screen Capture_20200822194846](https://user-images.githubusercontent.com/35951442/90955515-9269b680-e4b0-11ea-91a4-00c878426731.png)

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that were created outside the developer-center repo.

I've checked and this issue no longer exists in deepin v20.5 with `deepin-music 6.2.8-1`. You can upgrade your system and see if that fixes this issue. If not, please create a new issue in developer-center repo and we'll look into it, thanks!
