### ISSUE TITLE
Sometimes exit the program and reopen it,  the play list filled just now is empty again

### ISSUE THREAD

**Issue by lidanger** [linuxdeepin/developer-center#3084]
Sometimes exit the program by click the exit menu, and then reopen it,  the play list filled just now will be empty again.

**Comment by BLumia** [comment]
Sorry for the late reply since we were not checking issues that were created outside the developer-center repo.

I've checked in the most recent version of deepin-music (`deepin-music 6.2.8-1` on deepin v20.5) and I can no longer reproduce this issue. If that still happens in the most recent version you can get, please open a new issue in developer-center repo and we'll look into it. Thanks!
