### ISSUE TITLE
Long lag when signing in after new boot (Arch Linux)

### ISSUE THREAD

**Issue by ktechmidas** [linuxdeepin/developer-center#3132]
Hi,

When I first sign into Deepin desktop after boot (after the lightdm autostart) I will have 20-30 seconds where nothing on the bottom bar will work and the time is missing in the bottom rightcorner.

Eventually the time will appear and everything will start working normally, but it's a significant delay. I'm running i9900k, 32GB RAM and a 2070S with nvidia drivers installed.

**Comment by BLumia** [comment]
According to https://github.com/linuxdeepin/developer-center/issues/2490#issuecomment-1073026728, this should be fixed in https://github.com/linuxdeepin/startdde/commit/68b8f01d10842035551062858c28b643ce3ab0e2 , but since Arch Linux still haven't package the version that contains the fix, I'll leave this issue open :)

**Comment by ktechmidas** [comment]
Hi,

I've flagged startdde out of date on the Arch repos, hopefully a developer will come in and do a build. It may help if you guys could do a "release" as the last one was 2019 and this causes confusion: https://github.com/linuxdeepin/startdde/releases/tag/5.0.1

**Comment by BLumia** [comment]
> It may help if you guys could do a "release" as the last one was 2019 and this causes confusion

Releases should be fetched from [tags](https://github.com/linuxdeepin/startdde/tags). Since deepin moves their workflow to internal GitLab instance after 2019 and after that the tags are synced to GitHub, the GitHub's Release feature isn't used.

We are migrating our development workflow back to GitHub recently (https://github.com/linuxdeepin/developer-center/discussions/3051) and we'll consider make use of GitHub's Release feature. For now, please check package update from the tag list. Thanks!

> I'll try to build latest master myself and drop it in, see if that fixes my issue in the meantime :)

Feel free to let us know if you got any issue while the building/packaging process :)

**Comment by BLumia** [comment]
Should be fixed after upgrade to `startdde 5.9.32-1` or newer version :)
