### ISSUE TITLE
Bugs in Spin Fedora 36 with Deepin version 20.2

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#3138]
Hello Deepin/Fedora 36 Team

I recently installed Spin Fedora 36 with Deepin version 20.2 through Fedora-"Everything-netinst-x86_64-36_Beta-1.4.iso" in Boxes and I could see the following situations that need to be corrected for better Distro stability.

1º Below are data from the Distro and Hardware:

```
OS: Fedora Linux 36 (Thirty Six) x86_64 
Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-6.2) 
Kernel: 5.17.3-302.fc36.x86_64 
Uptime: 20 mins 
Packages: 1768 (rpm) 
Shell: bash 5.1.16 
DE: Deepin 20.2.2 
WM: KWin 
Icons: bloom [GTK2/3] 
Terminal: deepin-terminal 
CPU: Intel i3 540 (4) @ 3.059GHz 
GPU: 00:01.0 Red Hat, Inc. Virtio GPU 
Memory: 1560MiB / 7445MiB 
```

2º Distro fully updated with the latest versions of software and apps

![DeepinScreenshot_dde-desktop_20220501150632](https://user-images.githubusercontent.com/32621790/166158765-edf32348-709c-4e64-abc6-dbbfa781675d.png)

3º Common errors when opening some windows, where they close by themselves after some kind of crash and already reported to BugZilla.

![DeepinScreenshot_dde-desktop_20220501133950](https://user-images.githubusercontent.com/32621790/166158879-749cf788-0aa5-4419-afc7-433e0b25e4fb.png)

4º  When recording an image and saving it to the desktop, it is actually saved, but when opening the window, the information that appears is that the file has been removed or deleted and the file is actually on the desktop.

![DeepinScreenshot_20220430135804](https://user-images.githubusercontent.com/32621790/166158988-285c8e50-70ce-4531-881b-18a40330e0e8.png)

5º Screen resizing sometimes does not minimize or maximize by clicking on the icons of the open window, where to resize the screen you need to click on the window icon on the taskbar.

6º  When clicking with the right mouse button on the taskbar and clicking on Dock settings the window does not open.

![DeepinScreenshot_20220501134348](https://user-images.githubusercontent.com/32621790/166159250-13fd5862-e794-44f3-a80e-76a9675f779a.png)

7º  Sometimes it doesn't work and the option to add icons to the taskbar doesn't appear when any of the windows is opened or closed.

![DeepinScreenshot_20220501134718](https://user-images.githubusercontent.com/32621790/166159274-0494dd4b-4b6a-452e-8342-b11be2d19722.png)

8º After desktop enters the rest screen, when returning typing the password on the login screen, the desktop does not open.

![DeepinScreenshot_20220501143008](https://user-images.githubusercontent.com/32621790/166159320-d914ba9d-3fd2-43ec-bb57-8b5f582fdb4a.png)

9º In settings / Icon theme / no image of the icons selected or not appears.

![DeepinScreenshot_dde-desktop_20220501134957](https://user-images.githubusercontent.com/32621790/166159414-86b63589-18f9-4b26-8dc8-e0058761089b.png)

10º The volume control icon does not show the icon image on the desktop.

![DeepinScreenshot_20220501134645](https://user-images.githubusercontent.com/32621790/166159507-ce676a59-be35-42f6-8d22-39aac9b01b21.png)

11º In control center / customization / there is no way to scale the opacity of the taskbar and icon menu.

![DeepinScreenshot_20220501153423](https://user-images.githubusercontent.com/32621790/166159692-264c461b-43d6-4e40-b655-b689561fbe6c.png)

12º When we change the desktop wallpaper and when restarting, the wallpaper reverts to the previous default.

13º Looking forward to the Arch Deepin version 20.5 update which is more stable than this Fedora/Depin 20.2 spin. I hope the Arch team will update as soon as possible to benefit this Spin Fedora/Deepin partnership.

14º Hope next update comes with audio, video and deepin-screen-record apps

If you need any more details, I'm available.

**Comment by BLumia** [comment]
Hi, thanks for reporting issues. I took a glance at the issues and here are some things I have noticed for now.

Before we begin, instead of describing all the bugs in a single issue-thread, I suggest you create individual issues for each different bug/issue you have so it will make bug tracking much easier :)

> with Deepin version 20.2

We actually do suggest using the most recent release of DDE if possible. Arch Linux should already land some v20.5 DDE packages, and we're looking into the porting/packaging issues that are causing trouble to the package maintainers. If people who are reading this are package maintainers and have any issues while packaging DDE packages, please feel free to create a new issue so we could look into it.

By the way, some of the issues you've mentioned might be listed in https://github.com/orgs/linuxdeepin/projects/12/views/1 so it may be worth to take a look.

> it is actually saved, but when opening the window, the information that appears is that the file has been removed or deleted and the file is actually on the desktop.

![image](https://user-images.githubusercontent.com/10095765/166236336-4f8084df-b048-4d25-8230-7acca99f3c79.png)

It's likely a command line argument passed to the file manager but the file manager falsely opened it as a URL. Consider press <kbd>Ctrl+L</kbd> at this moment and paste the URL here.

There are other issues not covered in this reply. It's during the May Day holiday so we may get back to you about the details of these issues after the holiday (May 5th). Thanks again for the report :)

**Comment by BLumia** [comment]
I have tested the issues you've mentioned under deepin v20.5:

> 4º When recording an image and saving it to the desktop, it is actually saved, but when opening the window, the information that appears is that the file has been removed or deleted and the file is actually on the desktop.

This should no longer exists with `dde-file-manager 5.5.10-1` and `deepin-screen-recorder 5.10.15-1`.

> Screen resizing sometimes does not minimize or maximize by clicking on the icons of the open window, where to resize the screen you need to click on the window icon on the taskbar.

Works fine now under v20.5 with deepin-wm and deepin-kwin.

> After desktop enters the rest screen, when returning typing the password on the login screen, the desktop does not open.

There were related bug reports and it's closed since it's resolved, so I guess this should also no longer exists in v20.5 :)

> In control center / customization / there is no way to scale the opacity of the taskbar and icon menu.

Although the deepin distro doesn't have this issue, there were some KWin related porting issues that might related to this topic. Please check out the https://github.com/orgs/linuxdeepin/projects/12/views/1 board and search for `kwin`.

> Looking forward to the Arch Deepin version 20.5 update which is more stable than this Fedora/Depin 20.2 spin. I hope the Arch team will update as soon as possible to benefit this Spin Fedora/Deepin partnership.

We are working on DDE porting issues. Currently we're focusing on Arch Linux now, but we'll also look into all generic porting issues that happens on other distro. For the Arch Linux porting issue status, please refer to https://github.com/orgs/linuxdeepin/projects/12/views/1.

-------

So as a result, most of the issues could be resolved by simply upgrading the packages. But since we cannot directly work on downstream DDE packaging to address these issues, I'll close this issue for now.

If you are a downstream packager and having trouble packing DDE packages, please feel free to create new issue tickets to report the packaging issues so we can work it out, or email us at `support@deepin.org`, we'll do our best to help you resolve these packaging issues.

Thanks again for the report <3
