### ISSUE TITLE
AI Voice Assistant

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3143]
I have a question/suggestion, will AI voice assistant be available in English too and on global version of Deepin? 
![051459hxxfrzbub7f3pjzr](https://user-images.githubusercontent.com/98664445/167246169-9ef7c6a1-ab97-420f-95a5-35bda58e9b9a.png)

**Comment by BLumia** [comment]
Hi, 

The AI Assistant component in UOS is non-free, and the deepin team don't get permission to use this component in deepin, thus the deepin distro cannot include such component. And since we are the deepin community team, we cannot provide support to the commercial products provided by the UOS team. If you got any question related to UOS instead of deepin, please reach out the UOS team by emailing `support <at> uniontech.com` or other contacting method you see while you get the UOS system.

By the way, please consider use [the discussion board](https://github.com/linuxdeepin/developer-center/discussions/new?category=q-a-%E9%97%AE%E7%AD%94%E6%9D%BF%E5%9D%97) for generic non-bug report.

Thanks!
