### ISSUE TITLE
Deepin installed by Arch Linux official ISO does not go past the login screen

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#3210]

**Comment by BLumia** [comment]
I actually did a clean Arch Linux installation on a physic device (a laptop) via its `archinstall` with profile set to desktop:deepin, and it works without any issues (except the known issues tracked in [this](https://github.com/orgs/linuxdeepin/projects/12/views/1) project board).

Could you provide more information about your setup, e.g. what exactly did you installed DDE (via archinstall with profile "deepin", or do all the steps manually, or other ways?). If you are using `archinstall`, could you provide your configuration file for installation? If not, could you specify your installation steps?

**Comment by Octavian-Q** [comment]
> I actually did a clean Arch Linux installation on a physic device (a laptop) via its `archinstall` with profile set to desktop:deepin, and it works without any issues (except the known issues tracked in [this](https://github.com/orgs/linuxdeepin/projects/12/views/1) project board).
> 
> Could you provide more information about your setup, e.g. what exactly did you installed DDE (via archinstall with profile "deepin", or do all the steps manually, or other ways?). If you are using `archinstall`, could you provide your configuration file for installation? If not, could you specify your installation steps?

I see he is running it in a VM instead of real hardware, that could be the issue also 🤔

**Comment by BLumia** [comment]
> I see he is running it in a VM instead of real hardware, that could be the issue also 🤔 

I also have Arch Linux with DDE installation under VM but also don't have such an issue. Since it's an Arch Linux installation, detailed information must be provided since it can be a lot of possible combinations during the installation process, just knowing it's in a VM is not enough.

**Comment by serial02** [comment]
> Could you provide more information about your setup, e.g. what exactly did you installed DDE (via archinstall with profile "deepin", or do all the steps manually, or other ways?). If you are using `archinstall`, could you provide your configuration file for installation? If not, could you specify your installation steps?

Hello

 I didn't install anything special, I followed the standard installation.
 If only I could go into tty mode and check something, but it doesn't.
 It's the third time I've installed DDE with archinstall on a VM and the same thing happens.
 Note: I did different installs and the problem occurred every time.

**Comment by BLumia** [comment]
> I followed the standard installation.

There is no "standard" installation in Arch Linux, even if using the `archinstall` tool there can still be a lot of installation options. Please consider providing the installation configuration file so we can know what could possibility went wrong. Thanks!

> Other flavors install and log in normally

By saying "flavors", did you mean other profiles offered by `archinstall`?

**Comment by BLumia** [comment]
> I have no idea how to do it since I can't open the installed Distro. Can you give me an example or a way to do this?

Before you proceed the installation process, `archinstall` have an option to let you save your config file. Since you say you are using archlinux-2022.05.01-x86_64.iso then you should be able to see the option since the option is no difference from other options, like the one you choose the deepin installation profile.

Another way is, before you confirm installation, do a screenshot at the screen that lets you select stuff, since it will display the config that will be used to do the actual installation.

If you still don't know how to save the config file, you probably shouldn't use Arch... honestly.

**Comment by BLumia** [comment]
There is a screenshot I copied from the internet:

![image](https://user-images.githubusercontent.com/10095765/171659546-85b8bf8a-5316-4985-8137-44530a150887.png)
([source](https://news.itsfoss.com/archinstall-menu/))

The "Save configuration" option that above the "Install" option is what you want.

By the way, the setup I used 2 days ago (recalled from my memory):

- Using unencrypted regular `ext4` partition
- Not using swap
- Set a proper password for superuser `root`
- Add a regular user and set a proper password for it
- Using systemd-boot (doesn't really matter since I will switch to rEFInd during the post-installation process)
- Using network-manager
- Using desktop:deepin profile
- Using pulseaudio instead of pipewire
- Using the default 'linux' kernel
- No additional packages to install
- No additional repositories are enabled

**Comment by serial02** [comment]
Hello everybody

 I hereby inform you that the new archinstall 220601 ISO no longer has this error of not logging in on the login screen after installing ArchLinux with the DDE20.2 option.

 Thank you all for your help

**Comment by BLumia** [comment]
Just FYI, earlier versions (at least archlinux-2022.05.01-x86_64.iso and archlinux-2022.03.01-x86_64.iso) should also work fine. I'll close this issue for now. If anyone is facing a similar issue, please provide your `archinstall` configuration file or detailed information so we could look into it. Thanks!
