### ISSUE TITLE
Trying to change a wallpaper/screensaver crashes deepin

### ISSUE THREAD

**Issue by maxlefou** [linuxdeepin/developer-center#3557]
### SUMMARY | 问题概要

When attempting to select another background by using the right-click menu (is there another way to do this?? There should be) the desktop crashes making a random behavior like hiding the desktop icons, temporarily or just crashing and hiding the dock.

### STEPS TO REPRODUCE | 复现步骤

1. Right click on the desktop
2. Select Background and screensaver

### OBSERVED RESULT | 观察到的结果

The background selector appears briefly then the desktop crashes, either hiding the dock or the desktop icons.

### EXPECTED RESULT | 期望的结果

The wallpaper selector should appear and work.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

OS: Arch linux 6.1.8-arch1-1
CPU: Intel i5-9600K 370Ghz
GPU: Nvidia GTX 960 with official driver 525.85.05
Deepin: 20

### ADDITIONAL INFORMATION | 额外补充

Following arch wiki's indications, i use deepin-kwin. I don't know if it's related but i don't know how to switch to another wm for deepin, nor if it will change anything.

**Comment by BLumia** [comment]
Yeah it's still a known porting issue. Since v23 is going to be released soon, we will look into it once that happened.

As a workaround, you can use the image viewer application to switch wallpaper for now. If you are interested in hacking into the codebase, feel free to join [our matrix chat](https://wiki.deepin.org/Matrix) and we can offer some help if needed :)

Please track the follow-up of this issue at https://github.com/linuxdeepin/developer-center/issues/2283 and https://github.com/linuxdeepin/developer-center/issues/2445. Thanks!

**Comment by BLumia** [comment]
Oh, by the way, we have a porting issue tracking board here: https://github.com/orgs/linuxdeepin/projects/12/views/1

If you know any porting issue that wasn't on that board, feel free to let us know by submitting a new bug report :)
