### ISSUE TITLE
Very slow charging.

### ISSUE THREAD

**Issue by malwarebo** [linuxdeepin/developer-center#438]
I have Lenovo Thinkpad which has two batteries. It takes more than 5 hours to charge the laptop to 100%. It's very irritating. Kindly fix the issue.

**Comment by aiamuzz** [comment]
is this charging issue confirmed ... even i felt the charging was a little off ever since i upgraded to Deepin 15.5 ...

**Comment by hualet** [comment]
Do your machines have very heavy load ?

**Comment by aiamuzz** [comment]
i don't think so ... usually its only multi tab chrome and deepin-movie and occassionally a vmware virtual machine ...

the charging was very very slow when my machine was in standby(lid shut) ... this happened more or less around the 15.4 and 15.5 ... upgrade ...

**Comment by irfnhm** [comment]
No not at all. The battery was at 19% at 9 am in the morning when I plugged in the charger. I came back at 3 PM and the battery was at 98%. The laptop was completely idle.

**Comment by yyyeerbo** [comment]
What if you use another OS? like windows, is the charging speed faster?
I don't find any code in kernel related to charging speed, looks like it is totally decided by hardware.
maybe a charger with higher output voltage would be helpful. however, charging speed is also affected by temperature control circuit. thus even a charger with higher output voltage won't increase the charging speed. Also remember to use a charge that is supported by battery type, otherwise hardware may be destroyed.

**Comment by irfnhm** [comment]
Ths issue is only with Deepin. I used Windows 10, Ubuntu, Linux Mint before Deepin, all of them were good with charging. I think this is specific to Deepin.
My Laptop: Lenovo Thinkpad T460.

**Comment by irfnhm** [comment]
I am not using any 3rd party charger or battery, all of them are by the manufacturer. I can confirm that the issue is with Deepin OS only.
