### ISSUE TITLE
[deepin-wallpapers]: licensing discrepancies

### ISSUE THREAD

**Issue by bill-auger** [linuxdeepin/developer-center#4617]
### SUMMARY | 问题概要

thank you for sorting out the licensing recently - there have been open tickets about this in parabola and arch for years

https://labs.parabola.nu/issues/2986
https://bugs.archlinux.org/task/69882

i would like to add though, that there are still a few discrepancies - most significantly, the README still reads:

> deepin-wallpapers is licensed under GPL-3.0-or-later.

however, according to the new .reuse/dep5 file, only two files ('Makefile' 'blur_image.sh') have that license

the VCS also has in it, packaging recipes for arch and debian - the PKGBUILD declares a single license: 'GPL', which is incorrect - 'GPL' indicates the 'GPLv2-or-later' license, per arch policy - if the README is accurate, the PKGBUILD license should be 'GPL3' - if the .reuse/dep5 file is accurate, there are several licenses to account for in the PKGBUILD, depending on which files actually end up in the output package - in any case, none of those justifies the 'GPL' in the current PKGBUILD - the only license file which was ever in this VCS, was a stray/orphan GPLv3, which was arguably invalid anyways, until the recent clarifications

the debian/copyright file does not mention any upstream license, as it should - it is apparently declaring 'CC-zero' on the debian packaging files themselves, which is not the purpose of that file - the debian/copyright file is intended to indicate the upstream license(s)

also, at one point, the debian/control file had the package depending on the new non-free package - debian would not accept that into the main repo; because packages in main may not depend on anything non-free - that dependency was apparently removed recently - just noting it

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
current source
```

### PRE-REQUIREMENT | 预置条件

none

### STEPS TO REPRODUCE | 复现步骤

read and compare license declarations in the files: README, .reuse/dep5, arch/PKGBUILD, debian/copyright

### OBSERVED RESULT | 观察到的结果

all four files contradict the others

### EXPECTED RESULT | 期望的结果

license declarations are accurate and consistent

**Comment by bill-auger** [comment]
one last request - does anyone have the original source files for the images (project files for GIMP .xcf, photoshop .psd, etc)? - would it be possible to publish those also?

**Comment by BLumia** [comment]
Well, the license specified in arch/PKGBUILD and debian/copyright file might need to be updated to align to the one declared in the LICENSE file inside the root folder.

btw, packagers might need to update the license declared in Arch Linux's PKGBUILD as well, since there was licensing update in previous updates, which split some non-free wallpapers to separated package. cc @felixonmars

**Comment by bill-auger** [comment]
understood - that is discussed on the arch bug tracker now:
https://bugs.archlinux.org/task/69882

as for the LICENSE file, i forgot to mention that - that file is only a CC-zero license file - that file is not a license declaration - the only satisfactory license declarations in this repo are in the .reuse/dep5 file - the LICENSE file should probably be deleted - it is already duplicated as LICENSES/CC0-1.0.txt

**Comment by BLumia** [comment]
> as for the LICENSE file, i forgot to mention that - tha file should probably be deleted - it is already duplicated as LICENSES/CC0-1.0.txt

I'm not sure if that's the case, the file is here for the following reason:

1. The LICENSE file in the root folder of the project is used to indicate the overall license that the project is (or will be) licensed as. A project might contain several files that use different licenses than the one used by the project itself, those license files will also be inside the LICENSES folder. (e.g. a project was licensed under A, but the source repo reused code that was licensed under B and C), then the LICENSES folder will contain both A, B and C's full license text file, but the one inside the root folder will be A)
2. Online git hosting services like GitHub, GitLab and Gitea won't detect and display the license in .reuse/dep5, so the LICENSE file can be a hint to those services to let viewer know the license we used at a glance.

We actually would check if we can omit the license field in the `archlinux/PKGBUILD` file *we* provide if possible, since that file is purely for CI build purpose instead of for generating a proper redistributable Arch Linux package.

...but anyway the one we used in `LICENSE`, `debian/copyright`, `archlinux/PKGBUILD` and `.reuse/dep5` should be the same and have no discrepancies.

**Comment by bill-auger** [comment]
but why would you consider CC-zero to be the main license? - none of the significant files have that license - the only reason that anyone would want this package, is for the images, which are now denoted as 'CC-BY-3.0' - if any, that one should be considered as the main license - distributors could easy delete everything except for the images; and no one would miss those - there is no value in declaring any "main license", not even philosophically - for the purpose of distribution, _all_ licenses in the distributed package are equally significant

**Comment by BLumia** [comment]
> but why would you consider CC-zero to be the main license?

Well, I didn't mean CC0 should be the main license. I only say the LICENSE file inside the root folder is the main license and there shouldn't be discrepancies between `LICENSE`, `debian/copyright`, `archlinux/PKGBUILD` and `.reuse/dep5`. We'll check if the LICENSE file inside the root folder (and other files as well) needs to be updated.

We'll check this issue in the next work day (June 5) and will reply to this issue thread when the necessary changes are done :)

**Comment by bill-auger** [comment]
the README file also declares a license, although vaguely - but that one is the most obvious - i would add all of the relevant licenses to that file, or else remove the mention of any licenses from it

**Comment by BLumia** [comment]
Sorry for the late reply, this issue should now be fixed by the linked PR above. If there are still remaining issues, please feel free to let us know. Thanks again for the report!

**Comment by bill-auger** [comment]
much better, thanks - i noticed one discrepancy though

the copyright information is conflicting for the deepin/*.jpg files

> Copyright: UnionTech Software Technology Co., Ltd.
> Copyright: 2017 Deepin Technology Co., Ltd.

unless those are the identical legal entity, at least one of them, and/or the date '2017' must be incorrect

```diff
diff --git a/.reuse/dep5 b/.reuse/dep5
index 07eeb60..e262b6e 100644
--- a/.reuse/dep5
+++ b/.reuse/dep5
@@ -26,4 +26,4 @@ License: CC0-1.0
 # images
 Files: deepin/*.jpg
 Copyright: UnionTech Software Technology Co., Ltd.
-License: CC-BY-3.0
+License: CC-BY-4.0

diff --git a/debian/copyright b/debian/copyright
index 9c8b1a2..d4e25f7 100644
--- a/debian/copyright
+++ b/debian/copyright
@@ -18,3 +18,6 @@ Unless expressly stated otherwise, the person who associated a work with this de
 When using or citing the work, you should not imply endorsement by the author or the affirmer.
 
   see https://creativecommons.org/publicdomain/zero/1.0/deed.en
+Files: deepin/*.jpg
+Copyright: 2017 Deepin Technology Co., Ltd.
+License: CC-BY-4.0
```
