### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by malwarebo** [linuxdeepin/developer-center#489]
All of a sudden the sound stopped on Deepin OS powered laptop. Any solution??

**Comment by Peuczynski** [comment]
No idea, but this maybe caused by audio chipset, they tend to be buggy. First of all check if the output in control panel > audio > advanced is selected properly. Poweroff the machine (reboot sometimes doesn't work). Then open alsamixer from terminal and check if the channel you may need is not muted. I this there is more I can suggest

**Comment by irfnhm** [comment]
I tried all these. Still unable to get the sound.
