### ISSUE TITLE
Control and keep sound output more granular

### ISSUE THREAD

**Issue by trading-peter** [linuxdeepin/developer-center#581]
I sometimes like to set the sound output of some application (like a game for example) to my headset while keeping playing music on the speakers.

The settings panel doesn't seem to provide an option for this, so I tried to use PulseAudio Sound Control.
This does work in terms of defining were to output what application but there is one problem.

As soon as I hit the volume keys Deepin overrides the output settings again and i have to redo them with PulseAudio. Is there a way to change this?

**Comment by hualet** [comment]
@jouyouyun @electricface

**Comment by jouyouyun** [comment]
@pkaske can you upload a video for your settings process?

**Comment by pkaske** [comment]
@jouyouyun I recorded the following video to show what I do and what I want to accomplish.
I had to zip it for the upload. A gif wasn't an option because I talk in the video. Hope it helps to understand what I mean.

[simplescreenrecorder-2018-08-09_11.44.14.mp4.zip](https://github.com/linuxdeepin/developer-center/files/2273696/simplescreenrecorder-2018-08-09_11.44.14.mp4.zip)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
