### ISSUE TITLE
Resizing the file manager's window cannot be stopped

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#641]
https://youtu.be/-aNKKi68N44

**Comment by antechdesigns** [comment]
I also get this, not very often but I do get it, does it with the terminal sometimes, I will post a log if I get one.

**Comment by hualet** [comment]
@es20490446e anyway to reproduce this ?

**Comment by es20490446e** [comment]
As in the video?

**Comment by es20490446e** [comment]
If I touch the screen, it doesn't obey.

**Comment by zccrs** [comment]
@es20490446e Which window manager are you using?

**Comment by es20490446e** [comment]
```
$ wmctrl -m
Name: Mutter(DeepinGala)
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: N/A
```

Deepin Mutter 3.20.34

**Comment by keybreak** [comment]
I also have it on both of my test machines, it happens occasionally with touchpad / mouse doesn't really matter.

**Comment by keybreak** [comment]
@hualet @zccrs @BLumia 
I know it's not easy, but i've found reliable way to reproduce this bug in Manjaro Deepin:
1. Open Deepin file manager in **/** , stick it to right half of the screen
2. Right mouse button on any empty place in folder
3. Hover mouse over **Open in new window as admin**
4. Press Ctrl + Alt + A to take screenshot
5. Choose whole screen area
6. Choose text-tool and place it somwhere on right side of the screen, write anything
7. Press ESC, than ESC again to get out of screenshot tool
8. now try to move mouse left - Deepin file manager will stick

It's reproduceable on both of my real test-machines and VM on Manjaro Deepin.

Please fix it, because no matter how hard it is to get reproduceable effect, in reality usually it just randomly happens with some windows)

**Comment by keybreak** [comment]
Here's video just in case, https://i.imgur.com/4SY1Qgh.mp4

**Comment by antechdesigns** [comment]
I can confirm this does happen sometimes, I have to right click for it to release the grabbing of the window, very random.

**Comment by BLumia** [comment]
Not sure but did this still happends with DDE and qt5dxcb-plugin 1.2.0 ?

**Comment by cheese** [comment]
Just tested with qt5dxcb 1.2.0 but the issue does not change

**Comment by BLumia** [comment]
> Just tested with qt5dxcb 1.2.0 but the issue does not change

Yep I know (#1086), but at least it should works fine under DDE, since @es20490446e reported this issue within DDE so I would like to ensure if it works now :)

**Comment by es20490446e** [comment]
Do you need any further info?

**Comment by BLumia** [comment]
> Do you need any further info?

Did your issue still happens in the most recent version of Deepin? Thanks.

**Comment by keybreak** [comment]
@BLumia 
I can confirm it happens in all recent versions of Deepin and always did.

With Linux Deepin 15.10 Stable on Kwin maybe little less - yet still happens.

But it's really easy to see if you try Arch Deepin + deepin-kwin, you don't even need to do anything just try to move or resize window - it will stuck.

With deepin-mutter it is still reproducible by https://github.com/linuxdeepin/developer-center/issues/641#issuecomment-463628381, but without this trickery it just happens randomly.

**Comment by BLumia** [comment]
I'm sure it will happens under Arch or Debian (I got Arch and Debian installed on my two different laptop) due to qt5dxcb-plugin (yep, it's not a kwin issue) uses Qt's private header to implement some feature, so I want to ensure if it also happens under Deepin. Accroding to @justforlxz it may not very easy to fix but it's pretty weird since all my machine with Deepin installed doesn't have issue.

> With Linux Deepin 15.10 Stable on Kwin maybe little less - yet still happens.

Thanks for the info! It's still very weird, though.

**Comment by keybreak** [comment]
just double checked my reproducible trick, happens on:
- Manjaro Deepin stable with deepin-qt5dxcb-plugin  1.1.27-1
- Arch Deepin with deepin-qt5dxcb-plugin  1.2.0-1

So are you sure it's connected to deepin-qt5dxcb-plugin?

> Thanks for the info! It's still very weird, though.

Weird - yes and no, because Arch Deepin kwin is somewhat different from Linux Deepin 15.10 stable deepin-kwin (more animations, little less bugs)...

I think something still missing in Arch Deepin's deepin-kwin implementation.

> but it's pretty weird since all my machine with Deepin installed doesn't have issue.

Now **that** is really weird, since i can reproduce it on 3 real machines and all of my VMs...
There must be something else different

**Comment by BLumia** [comment]
> So are you sure it's connected to deepin-qt5dxcb-plugin?

No sure, but probably. As I said it use Qt's private header so you should also consider the Qt version differences. Since this issue got reported before dde-kwin project start, and my LXQT installation using xfwm as the windowmanager, so it definitely not a KWin issue.

**Comment by keybreak** [comment]
Current Manjaro Deepin qt5 packages versions, if it helps:

![image](https://user-images.githubusercontent.com/47599989/57838199-eaedd680-77cc-11e9-8d1e-043eccbde71f.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
