### ISSUE TITLE
Dock tray hiding

### ISSUE THREAD

**Issue by dusatvoj** [linuxdeepin/developer-center#650]
## Describe the bug

I hate hiding icons in system tray. Is there any way to disable hiding? (I mean that popup with redshift icon)

## Screenshots

![image](https://user-images.githubusercontent.com/11560794/47967528-750af480-e05e-11e8-8b72-76a96c1e5974.png)

### Distro & Version
 - Arch linux
 - Newest deepin desktop package

**Comment by antechdesigns** [comment]
@dusatvoj I have looked everywhere to turn it off, no joy. You can drag the icons from it though, its a bit annoying because sometimes if you don't hit the icon right it flies back in.
dde has got really buggy of late, all started since they added that hide tray icons & show desktop, Hopefully all will be fixed soon.

**Comment by hualet** [comment]
@antechdesigns is it happening a lot ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
