### ISSUE TITLE
[dde-file-manager] Hiding recent and sorting sidepanel

### ISSUE THREAD

**Issue by dusatvoj** [linuxdeepin/developer-center#651]
## Describe the bug

How is it possible to hide "recent" in side panel and sort User directories (as desktop, downloads, etc.)? 

### Distro & Version
 - Arch linux
 - Deepin desktop (newest package from repo)

**Comment by antechdesigns** [comment]
deepin file manager is hard coded, so what you see is what you get.

**Comment by hualet** [comment]
@wangjia12 @zccrs

**Comment by BLumia** [comment]
> deepin file manager is hard coded, so what you see is what you get.

You can actually hide *Recent* entry from the file manager setting dialog.

**Comment by antechdesigns** [comment]
> > deepin file manager is hard coded, so what you see is what you get.
> 
> You can actually hide _Recent_ entry from the file manager setting dialog.

OMG your right, sometimes its right if front of you ;) thanks @BLumia

**Comment by dusatvoj** [comment]
And what about sorting (alphabetical or manual) sidepanel user directories?
![image](https://user-images.githubusercontent.com/11560794/48205806-26ff3500-e36d-11e8-8d87-f31ccc28c6c4.png)
I think that this is not good order :/

**Comment by dusatvoj** [comment]
My proposal is enabling sorting by mouse in this section. As easiest way IMHO

**Comment by aiamuzz** [comment]
**I agree ... the user would be better of with an option to arrange the left panel of the file manager ... **

- The spirit of User directories(shortcuts) in the panel ... **is for ease of access**

- A great feature provided by you to tag files and folders so they can all be in one place ... neatly organized ... **again the spirit of this is ease of access** 

- The new feature of 'Recent' category added to this space ... **again for ease of access**

**However the current sorting on the left side panel is anything but intended for ease of use !!!**

![deepinscreenshot_select-area_20181127212558](https://user-images.githubusercontent.com/3283676/49095391-634bf400-f28e-11e8-87a9-3cd28a8be014.png)

![deepinscreenshot_select-area_20181127212536](https://user-images.githubusercontent.com/3283676/49095390-634bf400-f28e-11e8-883c-74895e3a950e.png)


The 'Tag' category is placed way down in the order ... though the spirit of it is to create ease for the user but its placement is difficult ... when one has as many partitions as me (2 internal and 1 external hard disks) ... 


the creation of custom color coded categories are buried at the bottom and not easily accessible ... i have to scroll each time to the bottom to access the organized files/folders

> What’s your proposal?

**An ideal way out, would be to let the user decide the sort order of ... 'Mounted Partitions' ... 'User Directories' as per one's preferences ...**

For Example i would like my color coded organized categories, to be placed at the topmost(instead of the current bottom most place) of the panel on the left side ... I would like the user directories (Recent, Desktop, Downloads, Pictures, ... , etc) to be placed next in the order ... then we could have the mounted partitions ... again if there was an option for us to sort the mounted partitions as per our preferences ... i would probably like to place/sort the most accessed partitions high up the order followed by the ones that are minimally used lying down the order ...

Please note that these sort orders have to be retained in the same order in the 'file manager add dialogue box' as well ... 

I know a lot of suggestions ... but this will greatly enhance the overall user experience by letting the user decide where they want the most frequently accessed items on the left panel of the file manager !!!

**Comment by hualet** [comment]
Sounds reasonable, what do you think @wangjia12 @BLumia @shule1987

**Comment by BLumia** [comment]
Seems @dusatvoj would like to reorder the user directories and @aiamuzz would like to reorder these groups in the left sidebar. +1 for this feature request.

Maybe we need to discuss about the IxD about how to let user reorder groups, @shule1987 .

**Comment by aiamuzz** [comment]
Exactly ...

- ability to reorder groups
- ability to reorder the members of each group

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
