### ISSUE TITLE
Optimizing the new 'Recent' entry in the File Manager panel 

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#705]
Hi,

The new feature in the File manager which has a 'Recent' category seems to record all files that are uploaded or attached on websites through the 'File Chooser' dialogue box ... Don't you think the files that have never really been opened on the system should not be part of this 'Recent' list ?

Only those files / documents that have been opened / viewed on the system need to be part of this list.

Daily i upload quite a few images online ... and i see all these files showing up in the 'Recent' list, which i would not prefer it to be there ... These files that i upload are burying all other files in the recent list making this feature impractical to me.

I prefer only those files that i have opened and viewed on the system to be part of this 'Recent' list

**Comment by BLumia** [comment]
> seems to record all files that are uploaded or attached on websites through the 'File Chooser' dialogue box

No, we did write it to recent history when you try double clicking to launch the file, and this behavior will be removed in the next update(for deepin distro, if you are using other distro like Arch, the file manager app delivered by their package manager may already removed this behavior).

Since the recent file should be supported by the applications who want to use them, like an editor, or an image viewer, browser and etc, the file manager shouldn't record the usage status, but just display the result as-is. So whatever you use dde-file-manager or nautilus or any other file manager which support the recent file standard, you'll always get the same result.

> Daily i upload quite a few images online, and i see all these files showing up in the 'Recent' list, which i would not prefer it to be there ...

That's what your browser did, not the file chooser dialog. btw imo this behavior is okay since you are also using these files so these files should displayed in the recent file list.

See also:

https://www.freedesktop.org/wiki/Specifications/desktop-bookmark-spec/

**Comment by aiamuzz** [comment]
> That's what your browser did, not the file chooser dialog. btw imo this behavior is okay since you are also using these files so these files should displayed in the recent file list.

You mean to say the browser treats the files uploaded to website as having been opened ?
is that why those uploaded files are showing up in the Recent list ?

Can't this behavior of the browser falsely treating the uploaded file as being opened curtailed/or suppressed so it does not show in the recent list ? ... would be nice if you people ignored files the browser uploads from being populated to the recent list .

**Comment by BLumia** [comment]
> You mean to say the browser treats the files uploaded to website as having been opened ?
is that why those uploaded files are showing up in the Recent list ?

Yes.

> I think its not okay for the simple reason that one won't be needing such files to view anytime soon after having uploaded ...

So maybe you should ask the browser's support team for help. We can't do anything for this behavior since it's not related to the file manager at all.

**Comment by hualet** [comment]
It seems that it's not a bug of the OS, close for now.
