### ISSUE TITLE
Video freeze while Playing Online or Offline Video.

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#717]
## Describe the bug

*A clear and concise description of what the bug is.*

## To Reproduce

*We can fix a bug faster if we can reproduce the bug, so provide steps to reproduce the bug is very helpful for us.*

## Expected behavior

*A clear and concise description of what you expected to happen.*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

### Distro & Version

[e.g. Linux Deepin 15.7]

### Related package version

[e.g. dde-file-manager v1.7 (4.5.6.2-2)]

*If you are not sure about which package went wrong, you can provide a list of package and it's version which you thinks is probably related with your issue*

### Additional context

*Add any other context about the problem here. It will be very helpful for us to isolate the problem. We will ask for more details when needed so feel free to remove this section if you really don't know what to provide.*

**Comment by alexwender1** [comment]
On my computer, this problem comes from 15.7 Beta ... when .iso has been reduced in size. These anomalies have been declining since then, but they are still recurrent.

For example, you are watching a video on Youtube; and in a few seconds the image of the video freezes (Youtube video, not the system). With the picture frozen ... the audio will normally play back.

When you move the cursor or click any key ... the video unfreeze and returns to normal. Until freeze again.

These issues have occurred with Google Chrome (I have the Google repository attached) and with Deepin Movie (not Flatpak).

**Comment by gokhanyildirimlar** [comment]
> anomalies have been declining since then, but they are still recurrent.

@alexwender1 I have another issue [here](https://github.com/linuxdeepin/developer-center/issues/675). Please write your experience and useful information under that one since @sonald is trying to solve it. Additionally, this issue is completely empty and not helping anyone.

**Comment by sonald** [comment]
@alexwender1  thanks for the information. both Google Chrome and Deepin Movie use opengl rendering by default, and this is probably a driver issue.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
