### ISSUE TITLE
[archlinux] dde-session-daemon high CPU usage

### ISSUE THREAD

**Issue by JuanSeabra** [linuxdeepin/developer-center#78]
I don't know if it's related but after a while dde-session-daemon starts to consuming much CPU usage and then deepin control center freezes, everything works but control center is freeze on the screen

**Comment by oberon2007** [comment]
I have this same issue since the latest update, too. Almost at every login now. It's a lot more serious than the issues I used to have in the past with **filemanager-backend**...
When this happens it renders my system completely unusable.
Trying to kill dde-session-daemon processes doesn't seem to even work...

**Comment by demencia89** [comment]
What DM are you using?

**Comment by fasheng** [comment]
Looks the high CPU issue was fixed now especially after deepin-daemon built with go. But control center freeze issue is still there for dde-session-daemon may crashed some times. I will close the issue and open a new one if you are all the same case.

**Comment by alexandre1985** [comment]
My `dde-session-daemon` was at 100% until I killed it. It made my desktop unusable.
This problem hasn't been fixed.

**Comment by DasJott** [comment]
Definitely NOT fixed. See here:
https://github.com/linuxdeepin/dde-session-ui/issues/30

**Comment by DasJott** [comment]
Currently it is running between 150% and 180% sucking all CPU and draining the battery.

**Comment by moda20** [comment]
me too, i am having this problem too.
