### ISSUE TITLE
[Feature Request] 能否添加一个选项, 在 dock 上点击程序时不切换桌面

### ISSUE THREAD

**Issue by CareF** [linuxdeepin/developer-center#847]
现在 dock 上点击图标激活打开的应用时, 会在多桌面中切换. 
多桌面我的主要用途是分离不同的场景. 比如写代码的 IDE 和查资料的浏览器放在一起, 与水论坛, 看视频的浏览器窗口在不同的桌面. 比如我开着多个浏览器窗口, 根据需要放在不同的桌面时, 我并不希望在呼出浏览器时切换到其他桌面. 
能不能像其他 DE 类似, 提供一下选项, 使得在 dock 上点击激活打开的应用时, 不切换到其他桌面? 只在其他桌面有窗口的程序, 不显示在dock上.

**Comment by aiamuzz** [comment]
True ... it happens and its not a very good experience ...

currently if there is a terminal window open in workspaces 1 & 3 ... and browser open on workspaces 1,2 & 3 ...

### Current Behaviour : 
when i click on the browser icon on the dock in the 3rd workspace ... the toggle happens on the 2 open browser windows as well as the 3rd instance of the browser window in workspace 1 as a result the workspace is switched even though it wasn't intended.


### Expected Behavior :
Lets say i work on workspace 3 ... workspace 3 has only 2 open application's terminal(1 window) and browser(3 windows) ... so if i click on the the browser application icon on the dock in workspace 3 ... the toggle should happen only between the 2 open browsers in workspace 3 ...


In fact it would be a good idea to **move** the current implementation/behavior of switching/toggling open applications across all workspace only when ... lets say ... i press the Ctrl key and click on the open application icon on the dock.

If there is no Ctrl key is pressed then the toggling should happen between open windows within the active workspace only !

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
