### ISSUE TITLE
[Program request] crash handler

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#877]
I think there should be a crash handler for deepin programs. This way developers can fix bugs more easily and efficiently because the user doesn't have to report the bug on their own.

**Comment by aiamuzz** [comment]
Ins't user feedback created for the same purpose ?

**Comment by SiamSami** [comment]
But when a program crashes, then "User Feedback application" doesn't load automatically. Also, that program is made only for Deepin Linux and not for other distributions as well.

We can take Windows and KDE for example. On Windows and KDE, if a program crashes then the crash handler opens up automatically.
And by the way, KDE's crash handler is available for all Linux distributions

**Comment by hualet** [comment]
Good point :)

**Comment by aiamuzz** [comment]
@hualet ... not sure if you want me to open another issue for this request ... let me know if so ...

Crash Handler is a good idea and it launching immediately after the application ends abruptly/crashes is a good way ...

Another use case where the applications have issues but do not crash ... (We already have this great KB shortcut for deepin apps ... `Ctrl + Shift + /` ... which displays a applet showing all the shortcuts for that application.)

@hualet ... wouldn't it be nice if this `Ctrl + Shift + /` would also copy important information to the clipboard ...

Information like ...
OS : Deepin / Arch / etc
OS update version date :
Kernel Version : 
Application Version : 
or any other info that may be required to help sort out the issue better.

With this info copied to the clipboard ... One could open a new issue here and paste the above information ... and directly jump to 'steps to reproduce' and 'expected behavior' section and report the issue.

**Comment by SiamSami** [comment]
@aiamuzz I think normal users/newbies would rather try to avoid keyboard shortcuts as much as possible...

**Comment by aiamuzz** [comment]
> @aiamuzz I think normal users/newbies would rather try to avoid keyboard shortcuts as much as possible...

Its an option to grab application information for us not normal users ... as you'd agree normal users don't visit github and report issues ... this shortcut information grab is for people like us who are active here on github reporting issues !

**Comment by SiamSami** [comment]
> > @aiamuzz I think normal users/newbies would rather try to avoid keyboard shortcuts as much as possible...
> 
> Its an option to grab application information for us not normal users ... as you'd agree normal users don't visit github and report issues ... this shortcut information grab is for people like us who are active here on github reporting issues !

Good idea I guess.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
