### ISSUE TITLE
Touchpad gestures

### ISSUE THREAD

**Issue by ositanachi** [linuxdeepin/developer-center#90]
I've been using Manjaro Deepin for a while and I've been loving it (even used Deepin before on another laptop). Anyway, I was wondering if Deepin could implement more touchpad gestures such as pinch to zoom, spread to zoom out, or a three finger swipe to work as alt tab.

**Comment by fasheng** [comment]
Using a three finger swipe to work as alt tab really is hacker's way ;)
In fact, we tried to support three finger gesture to support scroll-up/down, but looks not all touchpad works. So it  will be a hard work for us to support touchpad gesture for window manager.
Anyway, this is a good idea, let's just left it here.

**Comment by ositanachi** [comment]
Sweet! Since it will not work with all touchpads, would it be possible to stick the gestures under the Mouse and Touchpad settings in the future?

Three finger gestures aside, is ping to zoom and spread to zoom out with two fingers possible since two finger scrolling is implemented?

**Comment by fasheng** [comment]
I'm afraid not. It's possible that two finger scrolling is that the xinput drvier implemented it and the touchpad support it. For example, we could check if our touchpad support such features through `xinput` command:
```
$ xinput
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad                id=13   [slave  pointer  (2)]
⎜   ↳ TPPS/2 IBM TrackPoint                     id=14   [slave  pointer  (2)]
$ xinput list-props 13
...
        Synaptics Two-Finger Scrolling (274):   1, 0
...
```
But for the window manager, my understanding is that it could only catch the mock scroll signal instead of dispatching the two or even three finger gesture directly. So it will be some hard work to do if we plan to support such feature...

**Comment by ositanachi** [comment]
I'll be crossing my fingers!

**Comment by manateelazycat** [comment]
ositanachi , we have try to implement this feature before.
But, like fasheng said, not all touchpad support that.

The only way is build touchpad like Mac OS, all software way can't implement this.
