### ISSUE TITLE
Deepin Clone (arch)

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#933]
## Describe the bug
start 'deepin-clone' from the menu, enter admin password, nothing happens
start 'deep-clone' from terminal opens fine, does not ask for admin password

run 'sudo deep-clone' from terminal nothing happens, terminal output:

`$ sudo deepin-clone
[sudo] password for antech: 
[2019-02-21, 10:57:09.594] [Warning] [=>: 0] QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0
[2019-02-21, 10:57:09.604] [Debug  ] [dapplication.cpp=>Dtk::Widget::DApplicationPrivate::setSingleInstanceByDbus: 203] register service failed: QDBusError("org.freedesktop.DBus.Error.Disconnected", "Not connected to D-Bus server")
[2019-02-21, 10:57:09.605] [Error  ] [main.cpp=>main: 143] As well as the process is running
`
## Expected behavior
open deepin-clone prompting password 

## Enviroments:
archlinux fresh install & updated (as of this post)

I have no idea if deepin-clone should or would work on archlinux, never been able to run it. Can anyone confirm this? If its not to be run in archlinux can we have it removed?

@felixonmars 

Thanks

**Comment by felixonmars** [comment]
Since it's a GUI of partclone, most of its functionality should work when partclone works.

Some features like boot fix may not work since it uses commands from the apt/dpkg ecosystem.

@zccrs This seems to be a bug that `pkexec deepin-clone` runs without an error but no window was shown either. Also IMHO the executable should ask polkit itself for superuser privileges when it's not running under pkexec.

**Comment by zccrs** [comment]
Hi, What version of the dbus package?

**Comment by felixonmars** [comment]
1.12.12. Seems we have to improve the single instance implementation in dtk.

**Comment by zccrs** [comment]
> 1.12.12. Seems we have to improve the single instance implementation in dtk.

Yes, We are considering doing this.
